### ISSUE TITLE
Extension turn ON every time when i open Google Chrome

### ISSUE THREAD

**Issue by BonesKnows** [rainforestapp/tester-chrome-extension#101]
It is bad for users who share their computer with familly members.

**Comment by nishak14** [comment]
Either change from "Continue from where you left off" or ask family members to use different browser. BTW, you might want to use chromium if your family members like chrome. This extension works on chromium, too, and you can remove it from chrome.

I think this changes the scene. You may get hits the moment you start chrome/chromium because you are starting browser from where you left off without logging out. WoW. That is one good update.

**Comment by Phrogster** [comment]
Not only does it turn on when I open Google Chrome, it also turns itself on after I have turned it off and have Chrome open. 
This interrupts what ever I am doing at the time - and basically, scares me, because I thought I had it turned off!

**Comment by helloworld111gh** [comment]
fixed in #99

**Comment by Phrogster** [comment]
I don't have my browser set to "Continue from where you left off".

**Comment by erdeminofff** [comment]
A few minutes ago I lost a job because of this reason. I went out at home for a few minutes. When I wasn't at home, my mother opened chrome browser and extension had got a hit. (She knows, she doesn't touch the tests). Whereas, I was very careful about this subject. In next release, they must remove
