### ISSUE TITLE
Rainforest Keep It Up ............ Every Task Assigned showing Oops!!!! Nice Upgrades

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#109]
There are many people posting regarding this issue. But it seems no steps have been taken at your end Rainforest Team.

**Comment by helloworld111gh** [comment]
duplicate issue, see #106 or #49

**Comment by JPierreS** [comment]
@Deepak0988  This is because this is not an issue, it is normal due to the way jobs are assigned.

Let me give you an example.  On CrowdFlower when you try to access a task t hat has few units, will sometimes get the message that there is no work currently available.  If you refresh that screen you will eventually get work as units are added.   It is the same principle with Rainforest.  By the time the extension receives response that there is work, gets an URL, sends you the URL and opens it, someone else may have received the job.   What happens then,if there is no work available to assign to you you will get OOPS.  It is a normal process.   Keep in mind so many workers competing for work and clearly there is not enough work for every person :)

Right now works gets checked, URL sent to you, opened and work reserved.   To avoid oops they would have to check work, reserve work first, then send you the URL.  They are clearly working on this issue through hit reservation / and eventually push over web sockets.

OOPS is not a "problem" it can be a benefit even, you can refresh it (as the message states) (respecting the rate limit of course) until there is work to assign to you or close the tab and wait for another assignment.  This issue is present on CF as well with all tasks when there is no work available, same principle. :)

**Comment by Deepak0988** [comment]
Thanks For the explanation. Things got a lot clear now.

**Comment by pscohn** [comment]
Well put, @JPierreS. Closing as duplicate.
