### ISSUE TITLE
You have requested this job too often. Please return the work.

### ISSUE THREAD

**Issue by NeoWorker** [rainforestapp/tester-chrome-extension#120]
Got this message (title) after trying to refresh the page too many times because I was always getting the message: Oops. Something went wrong. What should I do about this? Did I lost the hit?

**Comment by renoid** [comment]
Same thing here. Two times today. I got "Oops. Something went wrong." or "Application Error".

**Comment by GreekGuy** [comment]
Same here. I got 4-5 tests where i could see the steps of the test and the terminal loading but after awhile... "Oops. Something went wrong"

**Comment by hunt40** [comment]
yes application error back now and after that they have more then enough tester 

next error you are requested this job too offen coming.....

i just have left 1 more refresh, after waiting more then 4 min,i am tired and sick of this problems and in the end we are punished because of their incompetence.and my tension high here and i lose another hit.i am tired and angry.

**Comment by JPierreS** [comment]
@NeoWorker : Unfortunately yes, if you get the message that you have requested too often, the job will gets assigned to another worker. Your only option at this point is to close the tab and wait for  another assignment.  Due to the session that was opened first, you will have to wait a minimum of 10min before receiving an assignment or 15min if you refreshed and lost a job past step 0.

**Comment by nerdatwork** [comment]
I think the poster was given a satisfactory response hence I recommend closing this thread.

**Comment by pscohn** [comment]
This is not an error, added some details here: https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained
