### ISSUE TITLE
Rejection for paid job

### ISSUE THREAD

**Issue by limsanto** [rainforestapp/tester-chrome-extension#124]
2 of my job get rejected due to bug, the real status of the job is accepted and i get paid already.

I try send email to Rainforest, but things keep happen, it will effect my job accuracy, please fix it soon.

below the respond from Rainforest

Hello,

It looks like the job may have been rejected due to a bug on our end that didn't show you were clicking things. I apologize. We are looking into what caused it. Unfortunately we can't reverse the rejection, but your account is still in good standing!

Sincerely,

Rainforest Support

**Comment by helloworld111gh** [comment]
"It looks like the job may have been rejected due to a bug on their end
that didn't show you were clicking things. They apologize. They are looking
into what caused it. Unfortunately they can't reverse the rejection, but
your account is still in good standing!"
From the support message you attached

**Comment by limsanto** [comment]
That email is 10 days ago, and today i still face that problem, hope they can fix it soon

**Comment by ahmedofhell** [comment]
I'm Facing the same problem. Reported (First Step) job gets rejected.

**Comment by limsanto** [comment]
@ahmedofhell, mine is get paid, but the status is rejected.
Hope they solve this problem soon, so it not make my job history more worse.

**Comment by ahmedofhell** [comment]
@limsanto I get paid too (4c).
Hope so.

**Comment by JPierreS** [comment]
If you are reporting an error / issue on step 1, make sure that initial link you pasted on step 0 marked with "-" was properly pasted and that it converted to another link (the site being tested).  if the initial link is unable to open for some reason, and you report on step 1, you will receive an automatic rejection as their system did not detect that the job was opened in the first place.
The initial link starts with app.rainforest..... (job signature URL).

**Comment by limsanto** [comment]
@JPierreS , it's seem you misunderstand our problem, we get paid for the job but the status is rejected, if rejected. why we get paid ???

**Comment by limsanto** [comment]
@JPierreS , it's seem you misunderstand our problem, we get paid for the job but the status is rejected, if rejected. why we get paid ???

**Comment by JPierreS** [comment]
@limsanto :  All jobs submitted get paid, whether you get rejected or not. In your case it was an automatic rejection due to the system not detecting that you opened the job (initial link was not processed).  Whether you get auto rejected or admin rejected, your job will still be paid  - it will also show as "approved" in your CrowdFlower inbox, that is a separate thing.  Status does not affect payment anymore.
You will get paid for every step you complete, (except the "-" steps and the side note step if any) regardless of the job status.  This has been the case now for quite some time, since the rejection disputes were removed. Now all submitted jobs are paid.
Also rejections are removed after 30 days.  Any rejection you receive in error will never count against you or affect your accuracy in any way or the amount of jobs you receive.
