### ISSUE TITLE
ACCOUNT STANDING: Blocked

### ISSUE THREAD

**Issue by neobuxianohd** [rainforestapp/tester-chrome-extension#126]
help my  my account  STANDING:Blocked
Reason for block: You have failed to follow instructions on too many jobs

how can I solve that?

**Comment by marius11** [comment]
You could try to contact them via the help button from your Rainforest profile page.

**Comment by JPierreS** [comment]
@neobuxianohd  All blocks of this nature are permanent. You may have received too many verified rejections or an admin determined that you have not properly completed many tests.

If you are certain that you have done nothing wrong and followed instructions you can request for an account review, in this case they will review your recent job history and determine if the block was fair or not.  Otherwise, if it was warranted, the block is permanent.

**Comment by neobuxianohd** [comment]
How I can request a review of my account?

**Comment by JPierreS** [comment]
@neobuxianohd  Only if you are absolutely sure that you have followed all the rules and worked correctly, you can contact support for an account review, they will check your recent jobs history and determine if the block was fair or not.   Do you recall what was the value under rejections (in your portal) before you got blocked ?

**Comment by pscohn** [comment]
@neobuxianohd If you feel your block was unfair you can contact us directly using the Help link in your profile, and we do a review.
