### ISSUE TITLE
Tooltip overlaps buttons 

### ISSUE THREAD

**Issue by nerdatwork** [rainforestapp/tester-chrome-extension#142]
The tool tip over YES "Click only if the instructions pass EXACTLY" overlaps all the buttons and after clicking Yes it still stays on when the next step shows up. It should automatically go away after few seconds.

**Comment by ChrisRaven** [comment]
Also, the tooltip could be displayed over or under the selected button, not at cursor. It will look much better.

**Comment by nerdatwork** [comment]
The buttons are quite self explanatory so tool tip shouldnt be there at all but that is just me.

**Comment by ChrisRaven** [comment]
True, they're not needed. But, I like some indication, which button I have clicked, because sometimes it happens, that I click a button (especially those in the test questions) and a second after I'm not sure, which one I've chosen and I wonder, if I did the question right. Actually, the first version (the one, where the selected button had changed background color to white) was best for me.

**Comment by nerdatwork** [comment]
Exactly. I have mentioned the same in the TEST NOTES. The clicked button MUST be blurred out to show which of the buttons was clicked. I get goosebumps thinking "Boy O boy this test gonna show up in the rejections for sure" since all buttons get blurred out.

**Comment by pscohn** [comment]
This will be fixed in the next release, which is scheduled for whenever our testers give it the :+1: :)
