### ISSUE TITLE
No payment.

### ISSUE THREAD

**Issue by Begushhij** [rainforestapp/tester-chrome-extension#146]
Actually, I was already tired to write in different instances.
The question is simple. Why I do not pay portal.rainforestqa.com?
Support silent.

Maybe that's the reason for this - http://fs5.directupload.net/images/160413/pdx2sfgi.jpg

**Comment by JPierreS** [comment]
@Begushhij  Since the payments are pending in your Rainforest account, there is nothing that CrowdFlower can do at this point.  According to the history page, you can contact Rainforest support for missing payments, after 48h has passed.   You would contact CrowdFlower only in cases where your Rainforest history shows no pending bonuses, but payments did not come through to your channel, after some time has passed of course.

**Comment by pscohn** [comment]
If you are missing some payment, you can contact our helpdesk through your profile.

**Comment by Begushhij** [comment]
Correspond with crowdflower useless. 
I can register a new account Rainforest?
