### ISSUE TITLE
Job abandoned 10 minutes from starting 

### ISSUE THREAD

**Issue by philips13** [rainforestapp/tester-chrome-extension#152]
Hello
I like to report that within 10 minutes of starting a 6 step testing in step 5 redirects me to Job Abandoned ( You were inactive for too long and the job has-been aborted . You May close this tab . )

**Comment by marius11** [comment]
https://github.com/rainforestapp/tester-chrome-extension/wiki/Idle-Policy

**Comment by philips13** [comment]
thanks marius11
But I was doing the job and was never inactive, was in step 5 and only 10 minutes had passed is test started .

**Comment by pscohn** [comment]
@philips13 do you happen to have the job id or assignment id?

**Comment by philips13** [comment]
I can not see the job ID or assignment, the link now looks like this: https://tester.rainforestqa.com/abandoned
this is my worker ID (20206661)
Thanks

**Comment by JPierreS** [comment]
@philips13 You can find the URL by looking in your history (CTRL-H) in Chrome.
If you have done other jobs after that and are not sure which URL, then next time you can immediately refer to the history if you get the abandoned message.

**Comment by philips13** [comment]
Ok. but I've deleted the history , also not returned to happen to me.
I close the subject or leave it open if it happens to someone else?
Thanks

**Comment by cookin2** [comment]
A similar thing happened to me yesterday.  I got a hit and was working on
something else.  I closed that down with "give up" because it was a timed
CF task.  When I click the "I understand", I got the job abandoned screen.
I'd never even seen a screen like that before!  I couldn't have been more
than a minute, 2 at the very most closing the other tab.  I'm sorry that I
lost the work, but more worried that some internal systems check is giving
me bad "marks" or demerits.  I didn't know how to save URL, thank you DS2
for the information :)  If it happens again, I'll know what to do and will
report it.

**Comment by JPierreS** [comment]
@cookin2 This is very strange indeed.  I have never had this before.

Since you were working on something else, is it possible perhaps you did receive this assignment much sooner and were not aware ?  The timer actually starts as soon as the job opens (the tester interface with the testing guide nodal).

**Comment by cookin2** [comment]
I was refreshing with ARP, the notification popped up the same way as it
always does, that's when I clicked give up on the other task.  I know well
what you mean about not knowing there was a "live" job.  That's happened to
me before so I know better than to leave an oops sitting there until it
converts.  In the beginning, I thought that when an oops converted, it
would take over and bring me to the job.  I learned the hard way that that
isn't the way it works lol

I'm 99% positive that it didn't sit there. I've had a situation where I did
wait too long - left it refreshing while I got a quick cup of coffee - not
quickly enough!  When I came back, there wasn't a screen like I had today,
it looked normal until I pasted in the first URL, then I got the message
inside the terminal that it wasn't active, forget the exact wording but the
terminal browser was white with a sentence in black telling me that it was
too late!  Yesterday wasn't like that, it was a screen/message that I'd
never seen before.

Even if ARP didn't notify me soon enough (that's never happened before) and
even if I had waited too long to start (which I'm pretty sure that I
didn't), I should have been able to try and start the task and then be
notified that I waited too long.  This was a totally different scenario,
clicked on the green button and then saw the Job Abandoned.

**Comment by helloworld111gh** [comment]
How long was the interval? ARP only checks at the end of the delay, so high
delay could be cause.

**Comment by cookin2** [comment]
I use the random interval option of ARP between 6 and 8 seconds.

The only problem that I've ever had was that while refreshing, RF told me
that I had already submitted the assignment, which I hadn't.

**Comment by cookin2** [comment]
I should have added that a few times, RF told me that I was refreshing too
quickly.  Those were times when things were very slow, so I waited a bit
and then adjusted the refresh time upward.

**Comment by JPierreS** [comment]
@cookin2  Refreshing too quickly would not cause the already submitted error - you would get instead a 'rate limit exceeded' error.  They hard coded the limit at API level for some time now, so it would be quite difficult to refresh too quickly ;)  The current limit for unopened jobs is a maximum 10 attempts per 60 seconds, and each attempt is cumulative.  Perhaps you refreshed a link from a completed job by mistake ?   In any case this would be unrelated to what you are experiencing now, as you opened a job and got a 'job abandoned' too soon.  

I have never had this happen before.  Would be interesting to know what triggers it though,
so the best thing to do next time you experience this, to send them the link of the assignment.

How frequently does this happen ?

**Comment by Genesis2015** [comment]
Idle timer is a good idea!

**Comment by limsanto** [comment]
mine even just about 5 minutes and get abandon

**Comment by limsanto** [comment]
job abandon when on progress doing it, make me very frustated
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx1adab8-5411-41e9-9885-016f8ae2e2dc&browser=any&hitId=4535734&sig=de7cc3bc1a6fe5de66112543a2e62aaf0277d5c0d6ff9039bd00e1b09f7a4e03&turkSubmitTo=%2Fthanks&workerId=29683750

**Comment by marius11** [comment]
Would it be ok to include other details on the "abandoned" page, like the id of the job (assignment id)? I cannot get the original link since it was over-written in the browser history with the new link.

It just happened to me while testing Rainforest's own app and received job abandoned after 5-10 seconds into a step. I had waited quite a while on a previous step because I kept receiving "Application Error" messages and red warnings on the page saying that something went wrong and the page needs to be refreshed. The site responded after some time and managed to go through two steps before receiving the message that the job was abandoned.

**Comment by Genesis2015** [comment]
Now everything seems to be good - I've got new hit and already
completed it. When
I said error message I meant to say "ERROR: Something goes wrong with the
server...". Never mind... If I still have problems, I will let you know.
Thanks for your support ;)

2016-05-11 21:01 GMT+03:00 marius11 <notifications@github.com>:

**Comment by sigitsenyo** [comment]
https://tester.rainforestqa.com/abandoned/
job abandon when on progress doing it, make me very frustated

**Comment by luisdanielvc** [comment]
True frustration comes when you have a 95 steps job and the abandoned screen appears at the last step, it happened to some friends.

**Comment by pscohn** [comment]
If anyone experiences an abandon near the beginning of a test and they were truly active the entire time, please send a ticket with the job or assignment ID.
