### ISSUE TITLE
"An Security error Occured (Error #2048) and Error 2031

### ISSUE THREAD

**Issue by nuevao** [rainforestapp/tester-chrome-extension#161]
Greetings friends, newly opened this task a few minutes ago and these errorres appears. in the terminal. refresh the page a few times but the problem continues.
![error1](https://cloud.githubusercontent.com/assets/16979522/14903152/0677880a-0d69-11e6-9813-afbd45090eb0.JPG)

**Comment by manishflyboy** [comment]
same here. continuously for 02 hits

**Comment by nerdatwork** [comment]
@nuevao I hope this issue is resolved and you dont face any more of this issue now since its 20 days old. According to recent updates they have added more servers so the jobs get loaded smoothly. If you dont face this issue anymore I kindly urge you to close this thread so Rainforest can focus on other open threads.Thank you.

**Comment by nuevao** [comment]
greetings, The truth is that not presented me more this problem, we thank you for your update and best wishes in their business.
