### ISSUE TITLE
Chrome extension opens jobs when set to "off"

### ISSUE THREAD

**Issue by kristen-allie** [rainforestapp/tester-chrome-extension#171]
@rainforestapp/tester-product A tester reported that the Chrome extension is opening jobs when it's supposed to be turned "Off". Can this be fixed? What other info can I provide here? Here's the message from the tester: 

```This is happening second time with me. I was gone outside of room after turning off the extension but when I come back to room I see one hit is abandoned. You know sir this is not my fault. Please Sir look after my account.```

**Comment by jbarber** [comment]
It seems unlikely.

**Comment by k65emil** [comment]
I can confirm it does happen at times even on v.1.2.5, though it hasn't happened for some time (2 weeks?). I would set extension to OFF and make sure it was showing OFF. Sometimes when I came back after 20 minutes, it would show NO instead of OFF. And some of those times a HIT would have opened, mostly then showing abandoned. A few times I came back just in time to do the HIT.

I'm not talking about leaving the computer and let extension set itself to OFF after a certain time. A HIT could come before it sets itself OFF, but I haven't experienced it. Purely when I intentionally have set it to OFF.

**Comment by pscohn** [comment]
Might be a symptom of the issue mentioned in https://github.com/rainforestapp/tester-chrome-extension/pull/99, if testers are logging in after turning off.

**Comment by tulko** [comment]
It happens more frequently now. You put "OFF" I hope no more than 30 seconds and is set ON. Not all the time, but sometimes tends to happen.
 I  close chrome when walk away from my computer.
Close chrome to not have many abandoned jobs.

**Comment by Genesis2015** [comment]
@tulko Same story here :(

**Comment by pscohn** [comment]
@tulko @Genesis2015  this is a new bug in the icon display, it should be fixed today.

**Comment by pscohn** [comment]
Closing unless there are new reports of this.
