### ISSUE TITLE
Terminal connection lost under test process

### ISSUE THREAD

**Issue by erdeminofff** [rainforestapp/tester-chrome-extension#175]
Don't let me write anything. I am so angry!.....

![yeni bit eslem resmi 8](https://cloud.githubusercontent.com/assets/8877357/15265463/ccce3d1c-198c-11e6-85ca-297fb91701f6.jpg)

**Comment by qpPykT** [comment]
Lucky-unlucky man :)

**Comment by ecliptica777** [comment]
easy test, but it takes time. do not get angry, be happy. :)

**Comment by GreekGuy** [comment]
Be happy i wish i could take tests instead of errors and no virtual machines......

**Comment by tulko** [comment]
It happened to me 3 times that. Today was a bad day for me in rainforest and I could do a few test, you're very lucky because I see that you can do test many steps, I get me a few of those

**Comment by sigitsenyo** [comment]
Hahaha ... that ever happened to me too ...

**Comment by nerdatwork** [comment]
@erdeminofff I feel your pain especially when you were at the last step and about to submit the job. The only thing that comes to my mind is if you had unknowingly passed the 60 min policy of Rainforest. 
Did you know you have to submit the job within 60 mins before its taken away from you ? I am only saying this since its 46 steps and that would definitely take around 60 plus mins in my opinion.

**Comment by JrRandy** [comment]
What are we supposed to do in these circumstances?  Any time I try to restart the test and it has a signup process it fails due to the email addy already being used.
