### ISSUE TITLE
Impossable to complete test after connection losing

### ISSUE THREAD

**Issue by nummuss** [rainforestapp/tester-chrome-extension#183]
After this issue some things may be already done on site and have to be done back, otherwise this is impossible to complete test.

**Comment by nerdatwork** [comment]
I guess you are trying to say is that you get "Connection Lost" message and when you try to refresh the page it says "This job is already done..." Please clarify a bit more so Rainforest and other fellow testers may give their advice/suggestions on fixing your problem.

**Comment by nummuss** [comment]
Well, I tried to say that instruction says to do something that looks like already done. I does not mean any message about it. Example: before losing connection I selected something to filter a table. After losing connection, I could not do this because the table was already filtered.

**Comment by pscohn** [comment]
@nummuss do you have the job ID?

**Comment by nerdatwork** [comment]
@pscohn I apologize for straying away from the topic in this thread but I couldnt get back to you since the thread is already closed. Its about https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained

You mentioned "Refresh the page to get a new VM." but as per recent AMA Mr. Russell Smith said you dont get a new VM even after consecutive refreshes and after 4 refreshes that VM is released and given to another job. Please clarify this and I will delete this comment as soon as you reply. Thank you.

**Comment by pscohn** [comment]
@nerdatwork he may have meant to say "job" instead of "vm", - on refresh, you get a new vm, but the same job. After 4 refreshes, the job is released and given to another worker.

**Comment by nerdatwork** [comment]
@pscohn Please check https://www.youtube.com/watch?v=igBS6_csYNw at 42:20 mark.

**Comment by pscohn** [comment]
@nerdatwork He's speaking about a work-in-progress feature that will allow you to press a button to get a new VM instead of refreshing. After that feature is released, you may get the same terminal upon refreshing, but currently refreshing gives you a new VM.

**Comment by nerdatwork** [comment]
@pscohn Awesome. Thank you so much for clarifying. Should I delete my posts since they are not relevant to this thread ?

**Comment by nummuss** [comment]
**@pscohn** No. I didn't remember the job ID.

**Comment by pscohn** [comment]
If you can't complete the test, click "No." If you run into errors like this you can open a support ticket and be sure to include the job id/assignment id or job link.
