### ISSUE TITLE
job abandon

### ISSUE THREAD

**Issue by yoges9** [rainforestapp/tester-chrome-extension#188]
got job abandoned  for a 52 step task 1 was on 47 step , terminal was very slow , frustrated ...

**Comment by nummuss** [comment]
The same with 18-step job

**Comment by nerdatwork** [comment]
@yoges9 If you spent more than 60 mins on a terminal completing the job, the job will be taken back from you and given to another work. This is as per the "Idle Policy" of Rainforest. If you took more than 5 mins to complete a step, the job gets abandoned. 

Please read through this carefully.
https://github.com/rainforestapp/tester-chrome-extension/wiki/Troubleshooting-&-Common-Errors-Explained

**Comment by qpPykT** [comment]
Are you kidding me? It is impossible to complete the hit with 105 steps in one hour. Not just clicked all the answers "yes". Do the hit properly! I spent about 40 minutes and I did about 35 steps. You need to put limits on the number of steps in the hits it just madness.

![rf-105-steps-1-1](https://cloud.githubusercontent.com/assets/4960092/15473839/b77da756-210a-11e6-86b5-1fd31a3af616.jpg)

**Comment by nerdatwork** [comment]
@qpPykT Send the same screenshot to tester@rainforestqa.com so they can talk to the client about the same.

**Comment by qpPykT** [comment]
@nerdatwork Yeah, I send it later. But without the limits it will last indefinitely, hits with a large number of steps will (be) come from the new customers again and again.

**Comment by macocha** [comment]
@qpPykT @nerdatwork I'm on it.

**Comment by qpPykT** [comment]
@macocha Ok, thanks for help. If you need link on this test [here](https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx7181f2-4996-4ef8-ab47-4d1a01931bfb&browser=any&hitId=3968366&sig=e9f0a22b8fdb915104fa951cb990cd50a042b83e43f1b7184f3606ee9bdad756&turkSubmitTo=%2Fthanks&workerId=31275106)

**Comment by ando100** [comment]
@qpPykT, @macocha, come on, seriously, this is really straightforward and quick test with mostly
all VERY short answers. Some TA-s put half a page of instructions into one step, here everything is separated.
If terminal works ok (important), you or anybody can do it under 60 mins. I just did and
had plenty of time to finish it.
And one just can not "yes" it, because later steps depend from earlier ones.

Please don`t take the joy from testers to once in a while to have tests like this :)

**Comment by qpPykT** [comment]
@ando100 As you did in step with email letter where other testers open a letter with your data that you entered earlier in the hit. Then you will not be able to continue to perform the test as the link in the letter already expired. If you chase for profit then you are probably in the wrong place. Better to do 3 hits on 33 steps and have time to spare, than 105 steps to do poorly just because of money.

**Comment by ando100** [comment]
@qpPykT, 

   Please NEVER use other person`s data to move on in YOUR test.

1. Follow the instructions EXACTLY and you will not mess with other testers letters/ emails.
2. Report ASAP if you see an error.
3. Submit a ticket, when you think, you were unfairly treated.
This test is one of most beautifully built up/ executed test I`ve seen,

Thank you.

**Comment by hunt40** [comment]
everday rainforest find  away to make me frutrated like a clocwork,, doing boues test site was slow and unresponsive still managed to almost finish it just before last step its directed to job abandoned screen

spend 30 minutes and i got job abandoned and that 30 minute wasted,thanks as always

**Comment by tulko** [comment]
can be test of the 105 steps, I remember it well, your first 3 steps are as one of most tests.

**Comment by diabolic012** [comment]
Got job abandoned right now. Terminal is like super slow to load pages and job has way to many steps and suddenly bam JOB ABANDONED. I am extra angry in the moment, spend time for nothing.
