### ISSUE TITLE
How can I change the ID numbers

### ISSUE THREAD

**Issue by SiSi72** [rainforestapp/tester-chrome-extension#215]
Tests open my site that I have not been entry and is closed.

I want to receive work only ID 33914476

Thanks.

**Comment by tulko** [comment]
I do not understand, you would only receive jobs that id 33914476,
  do only one test in particular?
I do not think it posiible. I think, a possibility  would qualify that test with 10 and another with a much lower number. I clarify that I'm speculating, but catches my attention because this test can mean less for you.
In my case I want more more more More and more test
Keep in mind that this test will be available a few times a day.
It will depend on when the costumer run it, or as a programmed in the platform rainforest

**Comment by nerdatwork** [comment]
@SiSi72 Can you please explain a bit more so fellow testers can help you if they can ? Are you trying to say you want to change your Crowdflower Id that is associated with Rainforest ? If so last time I checked its not possible as of now. If I have misunderstood you. Please explain more.

**Comment by SiSi72** [comment]
@nerdatwork You understand me correctly.

**Comment by pscohn** [comment]
You will be able to change accounts soon when we release new jobs on Crowdflower.
