### ISSUE TITLE
Since my account blocked...now help support was blocked too...very sad...

### ISSUE THREAD

**Issue by sigitsenyo** [rainforestapp/tester-chrome-extension#216]
Since my account blocked...now help support was blocked too...very sad...

**Comment by helloworld111gh** [comment]
Do not flood the Github forum with account issues.
You have already been told that the only possible solution is contacting
support. Do that or you will not be unlocked.

**Comment by sigitsenyo** [comment]
Look like I am really no chance again...
Hopeless...
Good bye all friend...
Wish you all luck...

**Comment by sigitsenyo** [comment]
@helloworld111gh 
Help support blocked too for me now...
I cannot acces that...
Sorry make you angre..
I am not annoying again...
Wish you always luck...
Good bye...

**Comment by JPierreS** [comment]
How do you know you are blocked from support ? Did you try sending a ticket through tester@rainforestqa.com ?  Don't try sending multiple tickets on the same issue.  If you are really sure you did nothing wrong and the block is unfair, you simply mention this to support and they will review your account history - if the block was unfair, you will be unblocked, otherwise, they do not reverse these blocks.  Sorry to hear that you are blocked.  Hopefully this was caused by a mistake and could be resolved.

**Comment by pscohn** [comment]
If you send a ticket we will get to it and see if the block was fair or not.
