### ISSUE TITLE
2 refresh every 30 seconds?

### ISSUE THREAD

**Issue by tulko** [rainforestapp/tester-chrome-extension#239]
last night I saw this new restriction, I thought I could get more jobs because there would be so many testers pressing "F5 F5 F5"
O great was my surprise I do not receive nearly tests
In the Month February return to rainforest, I was pretty well so far.
They are working on a new system for assigning jobs. But the changes that occur in the meantime are pretty bad.
I think they should improve:
- Allocating more jobs fair, which takes into account the quality of tests performed, number of bugs found, waiting time, number of rejections in the last 30 days. Ranking costumers. Etc.
- Currently the bound form of work assigned to you is your technical skills or your luck (I think, I'm not sure)
- The message ". There are no virtual machines Currently available Please retry in a few minutes" appears all the time, even if only to refresh twice every 30 seconds.
- I think your system would be fairer if more equitable.
- To have thousands of testers, if a few do most of the test
- Once you can do 50 test, I think it was coincidence.
- I respect the work of developers, but I must insist that a truly fair system would be best for Rainforest.

**Comment by aleksasf** [comment]
yup "great" improvement on "new" servers you anounced. Are you trying to get job done, or just make us watch "no virtual server" "another worker..." messages.
Extension pops-out 5 tasks none of them available for work, either "requested to many" either "no virtual machine" when time out passes you get "another worker" after refresh.
Not cool dudes, not cool

**Comment by nagabhyru** [comment]
Only 2 refresh in 30 seconds is not good idea most of us losing jobs because of this. every time extension pop out jobs it end in either "no virtual machine" or "another worker".

**Comment by khristianjose** [comment]
This isnt whort if extensions says YES and then i receive a message with, another worker or there are no virtual machines. Losing so many jobs cause of this.

**Comment by vladfuller** [comment]
I think 2 refresh every 30 seconds is worth ONLY  if we had almost 100% secured job when extension say "YES" ... if it doesnt happened you should let the refresh as before 10 every 60 seconds

**Comment by aleksasf** [comment]
I agree, make 1 virtual machine per worker reserved assign him work, and then you can raise refresh bar to 1 per min.

Current refresh is not productive at all

**Comment by JrRandy** [comment]
This change affected everyone, so does not give an advantage to anyone else over you.  Yesterday I completed 45 jobs on the 6 second refresh, today I have completed 21 jobs so far on the 15 second refresh.  I will see what I end the day at, but from what I can tell the refresh change had almost no impact to the amount of jobs I have been able to receive.  Please wait until you have some data in order to determine that in fact this has a negative impact before complaining about the change.

The reason for the change was to take load off the servers (1500 people refreshing every 6 seconds) in an attempt to improve the overall performance.  Lets focus on if you are seeing less latency within the VM's and less about how often you are allowed to hit refresh.

**Comment by tulko** [comment]
in the last 10 days or more lowered by 50% the jobs that I can do. it has not hurt me not helped me. I expected benefits. Whoever has less ping always have more jobs. I think

**Comment by khristianjose** [comment]
I think people with best conecction will allways grab a job when extension turn YES, but people like me will not because higher ping.
