### ISSUE TITLE
Adding more refresh time seems not helping.

### ISSUE THREAD

**Issue by uangonline** [rainforestapp/tester-chrome-extension#242]
Adding more refresh time seems not helping with all the error and lags and even worst, the Failed to report screenshot appear more frequent, and most of the time we have to refresh the job, since it wil never recovered from the error.

**Comment by aleksasf** [comment]
Magic improvements shhhhhh

**Comment by ecliptica777** [comment]
I think it is not worse than it was before. The system needs to be optimized - I think this is the first step.

**Comment by JrRandy** [comment]
The failing on screenshots, and the terminal server connection lost errors are worse IMO, but the ability to get jobs is the same, and the "No VM Available" errors are fewer from what I can tell.  But hard to tell truly when you sit in a 5 min test for 20 minutes because of the screenshot errors and lag :)

**Comment by pscohn** [comment]
We added refresh time to help control our servers with the addition of some new testers - it's still fair for everyone to get work, but we'll continue to work on the real problems with connection lost, vm availability, etc.
