### ISSUE TITLE
Can not switch IDs

### ISSUE THREAD

**Issue by mikesez** [rainforestapp/tester-chrome-extension#245]
Hello, I have two id (one from elite  and other from neobux), but I dont know how to get into elite profile, I suppose that I forgot an email address which I registered it with (because when I try the only one i remember it shows me my neobux id profile), is it somehow possible to get inside anyways if I have the "grab your profile" code? 

Please help, I have already wasted 6 dollars because it went in neobux which I have not used for years..

**Comment by mikesez** [comment]
P.S. I tried to find email when i was grabbing my elite profile, but it navigates me to a page with email filled-up, and it is the same email that i have in neobux id.. What should I do?

**Comment by marius11** [comment]
You should send them a support ticket.

**Comment by nerdatwork** [comment]
@mikesez The site from which you did the Rainforest job, that site's Crowdflower id is associated with your Rainforest profile. If you have claimed your profile by visiting the link you got in the Crowdflower notification then that is how you login to Rainforest portal. From what you are trying to say. You have claimed Rainforest profile from Neobux and Elite portals. Now since you cant remember which email you registered/claimed your elite profile with, you are unable to login to it hence all JOBS are paid to your neobux profile. If you click "**Forgot password**" link and enter the email that you have associated with ELITE, you will get the password to login to your Elite profile. If you forgot the email itself or used a fake one then you have to prove that you are the real/genuine user and Rainforest might be able to help you.
Please explain in detail what happened in the support ticket or email at tester@rainforestqa.com

**Comment by mikesez** [comment]
Yes I sent tickets but no reply for a long time :( 

Actually I am not sure if i used fake email or not, because it is really long time ago, but i have tried many of my emails and none working..

**Comment by nerdatwork** [comment]
@mikesez The support desk is filled with tickets so it takes time for them to reply back.

**Comment by mikesez** [comment]
Just a question, is it possible to have same email on both accounts? Cause when I click the address i used to claim my account 6 months ago, it leads me to page where i should fill my password, but the email is already filled and it is the same I have on my neobux id. (When I submit it tells me that this account is already claimed..)

**Comment by nerdatwork** [comment]
The already filled email is a "feature" of Chrome so if you remember the exact email you used you can enter that and proceed accordingly. Which two accounts are you talking about ?

**Comment by mikesez** [comment]
Solved now :)

**Comment by nerdatwork** [comment]
Great please close the thread.

**Comment by mikesez** [comment]
Ok, just for info, both accounts were on the same email and i could not get to acc which i wanted (must have changed email in the first account and then it was ok, but there are some bugs which are making it hard to reset your password..)
