### ISSUE TITLE
Submitted Hits not appear in Job History

### ISSUE THREAD

**Issue by mojenLXXXIII** [rainforestapp/tester-chrome-extension#25]
I have tested and submitted around 5 Hits using app.rainforestQA website in 6th and 7th DEC, unfortunately non of those hits was recorded in Job History list till this moment, 

does the persistence of Application Error related to this issue ? 
did anything changed regarding payment process ?

**Comment by vanessa180479** [comment]
Hi, I is happening exactly the same yesterday present several Hit and does not appear in the job history and no not me they have been paid for but if it appears as presented in total jobs, I should also note that this does not always happen that sometimes if it appears and normal payment but not others. Today I also happened this a hit and so far there appears with the history so no payment. Please if you could review the situation and tell me I must do my ID is 34208493

**Comment by vanessa180479** [comment]
just spent 2 hit again present at this time and this one would paid in history, and the second does not appear in the record ID 34208493

**Comment by KabakF** [comment]
I have same error too. for last 3-4 days I have missed bonuses(cents). They are counted in total job but I don't see them in "History" and not getting paid of them. It thought maybe my job was wrong so that's why they don't pay to me but now I'm sure It's not like that. Waiting for your for reply @pscohn 
(My Worker ID: 35273503)

Thanks. Have a nice day everyone :crown:

**Comment by nerdatwork** [comment]
History related issue: The hit id that shows up in the URL of the task doesnt match the HIT ID shown in history of RF. What should be considered as the reference point in this case ?

**Comment by remo24** [comment]
I've completed a 18 step hit 20 minutes ago and it doesn't appear on my rainforest profile history!

**Comment by KabakF** [comment]
@ukd1 @pscohn bosses, I just completed a job and I'm pretty sure I have done with it 100% correctly but I didn't get paid from it. I don't mind to work free for you sometimes but I don't think that's a normal thing to happen, It happens often this week. I'd be pleasured If you could take a look to this job. **Its HIT ID is 4474734** and **My Worker ID is 35273503**

**Comment by k65emil** [comment]
Will it help any if we give you the assignments URLs for hits not showing in history (and thus no payment)? I saved a particular troublesome one I did 1½ hour ago. When I filed bug report for it near the end, I got no response from your server even after several minutes. Had to redo the whole hit again. Only mentioning it because it could be related to it not showing in my history.
