### ISSUE TITLE
(REQUEST) - REMOVING SAFARI BROWSER

### ISSUE THREAD

**Issue by felipeinsanobr** [rainforestapp/tester-chrome-extension#255]
HOW WE ARE WORKERS RAINFOREST, I MAKE SURE HOW SO I AND MANY We think NEVEGADOR OF SAFARI IS VERY SLOW AND OTHER Hinders AT WORK.
US WHEN CAUGHT SAFARI JA FICO NERVOUS. IS COMPLICATED TO CATCH A 20 STEPS OF WORK ON SAFARI FOR ONE MORE THAN 80 STEPS ... PLEASE ASK OF YOU THE OPINION WORKERS FOR A RESPONSE TEAM RAINFOREST.

**Comment by nerdatwork** [comment]
@felipeinsanobr First of all writing is all caps is considered at yelling. I understand you are frustrated but that does not mean giving up on talking politely. Secondly Safari is for clients that want to test their websites/applications on iOS or MAC operating system so you cannot expect Rainforest to remove it just because you are unable to do the task.

**Comment by tulko** [comment]
Safari has some problems, but trust me improved a lot. I mention you have to consider that the staff is working constantly to make improvements

**Comment by pscohn** [comment]
We are also working on improving our metrics for our VM performance, which will help us debug and improve the terminals. As @nerdatwork says, we can't remove the VM because our customers need them, but in the meantime you can either check your network connection and make sure it's good, or provide us with more detail about what's not working properly.
