### ISSUE TITLE
3 rejections in a row and no time shown on history

### ISSUE THREAD

**Issue by kaytsu** [rainforestapp/tester-chrome-extension#264]
I did 3 HITS with the new interface and all 3 of them were immediately rejected. I have over 400 jobs completed with very few rejections. The 3 jobs all have no time shown on the history and no submit time listed but all 3 of them were completed to the point of me giving a rating and submitting. 

![image](https://cloud.githubusercontent.com/assets/20136128/16461725/8bc39052-3df3-11e6-853e-a85e3afe7402.png)

I tried sending a help ticket on the rainforest portal but it is giving me an error message to fill out the form (even though it is filled out) (I didn't include the email part but it is also filled out)
![image](https://cloud.githubusercontent.com/assets/20136128/16461983/c321f1a0-3df4-11e6-9353-bb55eef72cb3.png)

**Comment by qpPykT** [comment]
https://github.com/rainforestapp/tester-chrome-extension/issues/260

**Comment by kaytsu** [comment]
But mine weren't IOFFICE jobs - they were 'trendkite', 'rgnwldqa', and 'workforce-intuit'

**Comment by priggy** [comment]
i guess they have internal problem... it is not about particular job... its all up to their system... can you notice they rerolled back the CSS and design changes???

**Comment by kaytsu** [comment]
nope, I turned off rainforest after getting those 3 rejections and am waiting for stuff to be fixed....

**Comment by qpPykT** [comment]
@kaytsu 
Job Rejection Bug 2016-06-29 17:24:04 UTC, Kristen Hohenstein
Hello, dear testers! There's a bug with the new interface update that's causing some jobs to be unfairly rejected :( The team is working on fixing this bug now. When it's fixed, all unfair rejections will be automatically reversed! Since the fix is on the way, please don't send in a support ticket about this. We're very sorry for the inconvenience this caused!
