### ISSUE TITLE
Not getting paid.

### ISSUE THREAD

**Issue by jeffreyvdhondel** [rainforestapp/tester-chrome-extension#276]
As the title says i don't get paid for the jobs is complete :S.

Worker id = 22060024

<img width="890" alt="jobs" src="https://cloud.githubusercontent.com/assets/15087173/16502981/42c63f7a-3f11-11e6-8286-c8918dad5e59.png">

**Comment by JPierreS** [comment]
Which channel are you working from ?

**Comment by felipeinsanobr** [comment]
the system is too slow ... so the terminal both the payment in history

**Comment by jeffreyvdhondel** [comment]
Crowdflower is my channel. I did them yesterday i get these messages on my crowdflower account but no payment.
<img width="1160" alt="cf" src="https://cloud.githubusercontent.com/assets/15087173/16503868/543637de-3f15-11e6-8352-0a1f6b618915.png">

**Comment by Electroglitch** [comment]
You are not doing via Crowdflower Elite because i can see there is fee deducted from your payments,
according to cut percent looks like you're doing via Neobux if i'm right or some other channel  so problem is between Neobux or some other channel and Crowdflower it has nothing to do with Rainforest

**Comment by felipeinsanobr** [comment]
Good afternoon, you do not fully receive your payment because you work on another channel, the channel that you work takes a certain% of what you get.
the only channel that does not pay a fee, to my knowledge, is the EliteCrowdflower else you pay a fee if you do the Intagc, Neobux, Clixsense, Hunter, etc ... all of these sites take a fee from you and all other contributors.

I hope to have help.

**Comment by JPierreS** [comment]
@jeffreyvdhondel 
This is an issue between CrowdFlower and the channel you are working from. By channel, I mean ClixSense, Neobux, orther.   Do not worry about missing payments, once issue is resolved all payments will come through.  There may be a temporary issue right now.

Keep in mind some tasks are merged together and sent as 1 payment, so you may be getting 2 payments into 1, as an example.

Recently CrowdFlower changed how payments are sent through channels (payments sent by domain now instead of by IP).  Some channels are set up to receive via IP and have not made the changes yet.

From what I can see, there is no issue issue on ClixSense or Neobux at this time, so this may be unrelated.

You will have to contact the channel admin from the site  you are submitting those tasks from.

**Comment by nerdatwork** [comment]
@jeffreyvdhondel CrowdFlower is **not** a channel its a platform. CrowdFlower's Elite is a channel so is Neobux. As seen from the screenshot it is indeed notification of payment made to your Neobux account. Raise a support ticket with Neobux and ask them about your payments. Since Rainforest and CrowdFlower have already paid you.

**Comment by jeffreyvdhondel** [comment]
So i send Neobux a message the told met that the problem is with Crowdflower.
Send message to Crowdflower but the told me the problem is with RainforestQA.
Send them a message but still didn't receive nothing from them yet.

**Comment by jeffreyvdhondel** [comment]
After almoste a week and 3 tickets i got a message of RainforestQA yesterday.

"Hi there,

It looks like you are due to do training, which we are not paying for at this time. Once you complete the training jobs (this is about 8-10 very short jobs), you will be qualified for the real paying work.

Rainforest Support
rainforestqa.com
Read the Wiki: https://github.com/rainforestapp/tester-chrome-extension/wiki"

But i already completed the training on "2016-06-29"

So i have to wait again for a reaction :S

**Comment by felipeinsanobr** [comment]
Good afternoon, you do not fully receive your payment because you work on another channel, the channel that you work takes a certain% of what you get.
the only channel that does not pay a fee, to my knowledge, is the EliteCrowdflower else you pay a fee if you do the Intagc, Neobux, Clixsense, Hunter, etc ... all of these sites take a fee from you and all other contributors.

I hope to have help.

**Comment by jeffreyvdhondel** [comment]
@felipeinsanobr  No you don't understand me. I didn't receive **NOTHING** not even 1 cent.

**Comment by jeffreyvdhondel** [comment]
Yes i did so i have to wait again.

**Comment by jeffreyvdhondel** [comment]
Still nothing. Didn't expect that this problem takes so long to resolve :S

**Comment by JrRandy** [comment]
If the messages are showing up in crowdflower, they are receiving the payment from RF.  Otherwise, how would they know how much the bonus is?  Go to:  https://tasks.crowdflower.com/profile and match your Worker ID with the contributor ID to see where the payment is going.  Chances are, it is going somewhere you are not expecting it or to an expired neobux account.

**Comment by Ashok-Reddi** [comment]
@jeffreyvdhondel I am also facing same issue. moreover this I found some one else's jobs in my history page rather than my jobs. And the same thing in CF dashboard I got deducted messages but nothing is got paid in my eliteCF. The same thing is happened in my case too. RF asked me to finish the training jobs and I do well. After that I do 3 jobs but nothing is credited in eliteCF. If you found the solution please let me know the process to resolve this.

**Comment by jeffreyvdhondel** [comment]
@Ashok-Reddi Will keep you up to date. But good luck mate my first ticket is dated  June 21, 2016.
23 days and going. :(

**Comment by jeffreyvdhondel** [comment]
Update at my side still no contact from the Rainforest team there support is bad every BAD!

**Comment by jeffreyvdhondel** [comment]
And 8 days with NO response :S
@Ashok-Reddi Did you get a response?

**Comment by jeffreyvdhondel** [comment]
.. Still nothing its getting annoying.....
