### ISSUE TITLE
Rejected 3 Times for Providing Correct Answer

### ISSUE THREAD

**Issue by liladybugz26** [rainforestapp/tester-chrome-extension#282]
Hello,

ref: 6748291, 6748342, 6748368

I completed three HITs that asked the question: "Is there a signup form on this page". My answer was: "No, this is a login page that has a signup link, but there is **NO** signup form on **THIS** page. On my list of rejections, it says the question was: "Click Sign up!"  "Do you see a signup form?" This was **not** the question on the HITs. It never asked me to "Click signup".

Please see the attached screenshot for verification that my answers were correct.

My answer was correct, yet I was rejected internally three times. These three rejections now appear on my profile, and I'd like them to please be removed, and the HIT updated to reflect the correct answer so future workers completing this HIT are not wrongly rejected.

Thank You,
Rachael M Jones
#
![a7749f758fce42aca02df0b5a4ad4dc9](https://cloud.githubusercontent.com/assets/20234023/16509050/dfb15530-3efe-11e6-9d38-32aaa26ac34a.png)

**Comment by nerdatwork** [comment]
@liladybugz26 If the screenshot of the **Rejections** tab was posted maybe that will help to understand the rejection better. Also submit a support ticket by clicking the **HELP** tab in your Rainforest portal.

**Comment by helloworld111gh** [comment]
Did you send a support ticket? You would get a better response there, but...

You sure it didn't ask to click on the sign up link before checking if
there is one? Post a screenshot of rejection page to make sure.
On Jun 30, 2016 18:12, "liladybugz26" <notifications@github.com> wrote:

Hello,

ref: 6748291, 6748342, 6748368

I completed three HITs that asked the question: "Is there a signup form on
this page". My answer was: "No, this is a login page that has a signup
link, but there is *NO* signup form on *THIS* page. Please see the attached
screenshot for verification that my answers were correct.

My answer was correct, yet I was rejected internally (not on mTurk). These
three rejections now appear on my profile, and I'd like them to please be
removed, and the HIT updated to reflect the correct answer so future
workers completing this HIT are not wrongly rejected.

Thank You,
Rachael M Jones
[image: a7749f758fce42aca02df0b5a4ad4dc9]
<https://cloud.githubusercontent.com/assets/20234023/16509050/dfb15530-3efe-11e6-9d38-32aaa26ac34a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rainforestapp/tester-chrome-extension/issues/282>, or mute
the thread
<https://github.com/notifications/unsubscribe/AJs-6ZqUtHF6e-1Qw0ZnflA9X5F53fxNks5qRGmMgaJpZM4JCu8j>
.
