### ISSUE TITLE
so many connection lost

### ISSUE THREAD

**Issue by federicoall** [rainforestapp/tester-chrome-extension#283]
2 times i go not for report and notice  see job abandoned :/
![rf error](https://cloud.githubusercontent.com/assets/8026903/16509091/91fc00a2-3f07-11e6-845b-c3f46416cfee.JPG)

**Comment by nerdatwork** [comment]
@federicoall Please read this https://github.com/rainforestapp/tester-chrome-extension/wiki/Idle-Policy

**Comment by algset777** [comment]
@nerdatwork I have the same problem as @federicoall 

My problem is not related to the conditions listed in "Idle Policy"

**Comment by uangonline** [comment]
@algset777 The connection lost just become more and more frequent latelly.

**Comment by sweeneyapps** [comment]
I understand what you meant,  if I do 10 steps and I lose connection then refresh to get the VM back on my screen, I go BACK to step 1!!   It's SILLY!   Because we already did the work half way or even close to the end.   Doing task over again, we should be paid double for that!.   Unless they fix that bug.
