### ISSUE TITLE
 Rejections number to be locked account .

### ISSUE THREAD

**Issue by renangloor** [rainforestapp/tester-chrome-extension#297]
Hello , I wonder if there is a fixed or approximate number of rejections to be blocked, or rely on some percentage ? In my case I have 358 tasks done , 12 bugs found and 14 rejections , I can have more many rejections before someone gets locked out because I am concerned , and will only reset 13 .

**Comment by helloworld111gh** [comment]
check #271,
this is a duplicate, please close this

**Comment by nerdatwork** [comment]
As per the current rules you can have a maximum of 20 rejections after which your account is blocked. Also try to search the existing threads since most of the issues are already covered. If you are not satisfied by reading those threads and still face the issue, you can open a new thread. 

Whenever you read the replies and are satisfied with the response, please close this thread.
