### ISSUE TITLE
this assignment has already been completed.

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#336]
it show like i was worked on that job, but it just saying no virtual machine. Then after i reload, this message appear, i really don't understand, i hope that is not count  like abandoned job or some
![rf2](https://cloud.githubusercontent.com/assets/20422665/16930752/e4bb28ba-4d3d-11e6-95a9-391967303cac.JPG)
---------------------------------------
![rf1](https://cloud.githubusercontent.com/assets/20422665/16930751/e4b9ff9e-4d3d-11e6-945b-96aa9e326eb4.JPG)

**Comment by nerdatwork** [comment]
It happens when you are working on a job and there is some issue which makes you refresh the page. Then you get "NO Vms" message by the time you refresh it again, the job has already been picked and uploaded by another tester. I would advice you to make sure your internet is working fine when you get the job. For delayed payment please wait for 48 hours, if you are still not paid then file a support ticket.

**Comment by djux90** [comment]
but i didn't worked on job, it just came that message, and that is strange

**Comment by tulko** [comment]
I spend ever the same. as is not so common never report it, you do well in report
