### ISSUE TITLE
i couldn't clik on yes or no

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#343]
when i try to click on yes or no, nothing happened, i got job with 7 steps, but 2 or 3 times when i was on step 4, i couldn't move forward, no message error like failed screenshoot. I refreshed job and got Rate limit exceeded... That isn't first time that yes or no didn't work, i quees it is internet problem or some and it worked when i refresh page

**Comment by nerdatwork** [comment]
Can you take a screenshot of the page and post it here next time that happens ?

**Comment by djux90** [comment]
Yes, but on screenshoot you can't see anything cause it is all normal,  just yes or no don't work. I will post video when that happen again

**Comment by JPierreS** [comment]
@djux90  This is an issue related to the screenshot system. You will not always get the warning that the screenshot failed as it is still trying to reach the server.  Also make sure when you got your last failed screenshot pop-up that you did not click on the box to not warn you again.  Sometimes for whatever reason the screenshot system can be very slow, so when you click YES/NO button they will gray out momentarily until the screenshot is taken and it has successfully communicated with the server and received acknowledgement back - This process can take sometimes a minute or more depending on condition.  Just wait, eventually you will go to next step, otherwise restart if you notice it has not resolved within few minutes.  There might be temporary hosting issues or an application offline condition causing this issue, which is why it is advisable to wait as if you refresh your hit during an offline condition you will get an "application error" page and risk losing your hit due to request too often message.

**Comment by nihlathar** [comment]
According to the new rules if you encounter any problem at all you should report it, however, it's best to try and get a new terminal and/or wait a couple minutes (5-10, just make sure you don't time out) and try again.
