### ISSUE TITLE
New testers 

### ISSUE THREAD

**Issue by jeloy1** [rainforestapp/tester-chrome-extension#365]
Hello, I managed to take the Rainforest QA task but I have not even claimed my profile. I claim is that although they have already closed the acaptación of new devices? I repeat: I took the job, but had not yet claimed my profile. I can do it now?

**Comment by nerdatwork** [comment]
Claim the profile if you havent and install the Chrome extension to get more jobs.

**Comment by nihlathar** [comment]
Yeah it's a bit confusing, I don't know that it is explained anywhere where to actually find the link to claim your profile. You should see it on your profile on crowdflower, here https://tasks.crowdflower.com/notifications (if you use CF, if amazon mturk then I dont know where to find it). Make sure you're logged in on CF in order to see the page. If you've completed any tasks (and submitted your work), you should see a message with the link

**Comment by nerdatwork** [comment]
@jeloy1 Is your issue solved yet ?
