### ISSUE TITLE
4c Per Step If a Verified bug is reported. No Longer Available

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#371]
Few days before, during the bonus payments, 4c per step was given for all the steps available in a test, if a verified bug was reported. But today It is no longer Like that. Is this issue only with me?

**Comment by maciejgryka** [comment]
@Deepak0988 this was an experiment, which we finished yesterday. In short, for a limited time we were paying some workers for all steps after reported bugs to check whether this increased result quality for our clients. It didn't, so we put everyone back on the old system.

We always send emails about things like that to workers, who gave us their email addresses. Make sure your profile is up-to-date if you want to get the info in the future.

Happy testing!

**Comment by kaytsu** [comment]
For me personally, during that experiment if I got to a step with a bug I tended to: 
1-spend more time trying to make the page work - including refreshing and starting again in case it was user error and 
2-write more about the problem to help them fix it (because I knew I would get paid for the time spent trying to make it work). 
Before (and now after) I will write what didn't work but don't write as much or spend extra time trying to make it work/figure it out.

**Comment by Genesis2015** [comment]
@kaytsu Am doing the same things, but now... :(

**Comment by ando100** [comment]
@kaytsu and @Genesis2015 - Pheww...Gees..., You guys got it completely wrong. Sad about that :( You are never supposed to "fix" anything... You were supposed to report a bug/ error at sight, simple as that.

**Comment by kaytsu** [comment]
@ando100 I wouldn't try to "fix" the problem.  I said I would make sure it wasn't user error (me making a mistake) or write more about the problem (including that I had tried again or what other things happened) instead of just getting a bug and and saying simply "xyz didn't happen".
During the experiment I would write a few sentences about the step/bug. "xyz didn't show up on the screen when I clicked XXX button. I tried multiple times and refreshed the screen. The yyy button next to it does work but XXX button does not do anything"

**Comment by marius11** [comment]
@kaytsu Testers must report bugs, and not to find workarounds them.

**Comment by pscohn** [comment]
@ando100 and @marius11 are correct, and if you read the third rule:

"Do not perform any actions except for the ones for the current step."

This includes refreshing, re-trying, or doing anything other than what is suggested you do in the instructions.

**Comment by Genesis2015** [comment]
Under the statement "fixing the site" I meant that I wanted to be sure that the error is not because of me. For example: "Incorrect Log In info" error - I try to log in several times before to report the error. Sometimes I put some extra characters/space accidentally and this make errors. 
I was hoping that the experimental program will become a reality! This thought makes me even more careful. 
An Idea: you can use the program to reward people who work honestly. This will motivate them to work even better and will discourage the cheaters. Equal pay to all people, regardless of how well they work, I think, is not a good idea. This will simply create more contrast between people who work honestly and those who don't do it.
