### ISSUE TITLE
Strange error message

### ISSUE THREAD

**Issue by DrDejan** [rainforestapp/tester-chrome-extension#379]
Yesterday was chrome today ie11.
When i refresh page my computer try to connect with terminal but result is this message. After 4 refreshing job goes to often or already completed....

![cudno](https://cloud.githubusercontent.com/assets/17418506/17532049/07b46208-5e7f-11e6-899e-0c82788fefca.jpg)
![cudno2](https://cloud.githubusercontent.com/assets/17418506/17532055/0d4f5dc6-5e7f-11e6-9a56-d188503fc7dd.jpg)

**Comment by zfonck123** [comment]
i am loss 2 two job today for same error

**Comment by zfonck123** [comment]
![image](https://cloud.githubusercontent.com/assets/19192312/17533165/a044e9bc-5e51-11e6-907a-181148f12857.png)
this error each 30minutes affter 12pm :(

**Comment by DrDejan** [comment]
zfonck123, that message is nothing strange. I think that is result because can not connect to terminal....

**Comment by zfonck123** [comment]
maybe but for that and trying refresh many times get job obten too T_T

**Comment by nerdatwork** [comment]
@DrDejan The error means, the extension could **NOT** get a terminal with Internet Explorer version 11 i.e. **ie11** with a screen resolution of 1440 x 900. It is perfectly normal.

@zfonck123 Your error is different that what @DrDejan mentions. Please keep the topic related to same issues. Also the error message you see happens when the terminal faces issues in getting a terminal.

**Comment by DrDejan** [comment]
Question is, what i need to do when i get message ? Wait or refresh until job goes to often?

**Comment by nerdatwork** [comment]
You can refresh the page and if it says too often close the page and wait for next job.

**Comment by DrDejan** [comment]
OK, thank you.

**Comment by JrRandy** [comment]
DrDejan - I usually only see this message if I have to restart a job after losing connection.  If you wait 1-2 mins instead of hitting refresh right away, it can usually find the server you need.  I found that if I refreshed too soon, it couldnt find the right type of machine and then ended in "requested too many....".  I am assuming its because the server you were connected to was still hung up, and not freeing resources for the new server you are requesting but that is nothing more than an assumption.

**Comment by JPierreS** [comment]
All these new errors are due to the new interface and code changes.

They are not really new in the sense that in the past you would only see the same generic error message.  Now with the changes you will see a better representation of the actual errors experienced.

For whatever reason at the time the system was not able to get a specific terminal VM.  The only thing to do is refresh, but as a tip I recommend not refreshing right away, to reduce your odds of requesting too often., try to wait longer brefore refreshing.  There is no rush :) You have enough time to retry before losing the hit.   To be safe I'd give it 30seconds or more  ***NOTE: This will NOT completely eliminate the request too often, but you will give a good window of time for whatever issue to resolve.

And the extension does not give you terminals, it just polls the server for work state, if it finds work it will pass you a link, this link will do another call to the API and assign you the work if it is still available or if there are other assignable jobs you can work on.
