### ISSUE TITLE
Got 2 job abandoned while i still active

### ISSUE THREAD

**Issue by warpten09025** [rainforestapp/tester-chrome-extension#382]
First job has 25 steps , when i went to step 20 , suddenly my job abandoned . Then i refresh the page and it telling me "The job has been submitted" , so I think another tester has the same job id with me and they complete it faster than me . The 2nd job , after i just click the copy button ( the button outside terminal) then i see  that job abandoned  . I think someone stole my job , or maybe because the server has bug that give same job to multiple tester .

**Comment by nerdatwork** [comment]
Are you sure you are doing the jobs within the **Idle Policy** limits ?

**Comment by luisdanielvc** [comment]
It happened three times to me, i got a job and it was active less than one minute, then the abandoned screen appeared

**Comment by nerdatwork** [comment]
@luisdanielvc Are you sure you started the job as soon as you got the job ? It could happen that the job window was open for around 4 mins then by the time you finished doing the step it was 5 mins and you got job abandoned.

**Comment by JPierreS** [comment]
@warpten09025 :  There are 2 types of idle policies, the 1st one is effective as soon as you have a live HIT (let's call it step 0), you have 10 minutes to pass this initial step of copying and pasting the job link and taking screenshot.  From step 1 and onward, the policy is 15 minutes.  Each time you start a new step the timer resets. In your case you mentioned that you got job abandoned at step 20 correct ? So this means the 15 minute policy was in effect.  If you spent more than 15 minutes on that step it will revert to abandoned status.   And no, this is not caused by another worker completing faster.  The moment you get a live HIT, the work is assigned and reserved to you for the allotted time, nobody else can complete your work.

If you are getting abandoned messages having spent less than 15 minutes in a given step (1 to ~) contact support.  It is possible that the idle policy were changed internally at API level and not updated in the docs.  Otherwise there could be a bug, where if you RESTART a HIT again for whatever reason, the timer is not reset and continues (cumulative) which is not good. Report the JOB ID and have them look to make sure there has not been changes to the idle policy.  Also make sure you are not exceeding the idle policy time on step 0 and step 1 and onward.
