### ISSUE TITLE
is it posible to click on yes, but in rejection says you clicked on no?

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#389]
I got rejection for bad summing numbers, i am really sure that i answer YES, i had some problems with "something bad happened" mesage and must click few times but i am 100% sure that i clicked yes, but in rejections it wrote that i clicked on NO. Is it posible for that to be some error? That really annoyed me

**Comment by JPierreS** [comment]
It's unfortunate that this happened to you, but normally this should not happen.  It is easy sometimes to get distracted and click the wrong button.  In any case, the threshold for rejections is big enough to allow for such mistakes or issues if any.  Either way, the rejection you received an automated one and as with all rejections, will disappear after 30 days (each rejection has its own 30 days period).  Those type of rejections are not removed for whatever reason.  Try to pay close attention and if you notice this issue happening frequently you might want to report this, but generally this should not be happening.  If you click a button for whatever reason and there is an issue such as something bad happened, etc, the buttons will revert back and you would have to click them again.  I have experienced the same issue in the past ,but I must admit this is extremely rare.

**Comment by djux90** [comment]
i got one more rejections for this. And again i am sure i am not clicked wrong button. I don't know what to do? I must to record my test to prove that or something? Please some admin help, i using calculator and always double check

**Comment by JPierreS** [comment]
Is this always happening during "something bad happened" or other errors ?
If so this could be a serious bug :)  I would not worry much about it, you will not be faulted if there is a bug.  I guess it would be a good idea to contact support about this so they can forward this issue to the right team to take a look at.

Sadly, unless they have proof of an actual bug, they will very unlikely overturn your rejections for this.

**Comment by djux90** [comment]
in last days almost in every test i got few error "something bad happened" or some else erorr. But i checked now more carefuly from last rejection and again i am sure that i am not wrong. I writed to them, i don't need they overturn rejection, they will disappear, but i am worried if this continue. I will try to reinstal chrome, and will try to record every test, so if i got another one i have proof if they don't believe me. I know that probably they couldn't find bug, i know how things works, but still it would be goof if they can check it

**Comment by RnkSts** [comment]
I received one **rejection** for a wrong sum of numbers, I was shocked because it would be my first rejeccion in rainforest, maybe i get distracted and click wrong response how says @JPierreS . 30 days after it no longer appears in my history, but that was crazy how i can miss that sum (or a bug don't know **:v**) :open_mouth:  @djux90 Don't worry it will disappear soon.

This days I have been receiving many error messages while testing (Something Bad, Machine uncapable, etc) [Hope these messages get fixed and dissapear soon] and I not get missed robot questions or  something. But if you're sure that you are experiencing these bugs, record it, you will save other testers :hammer: :smiley:
