### ISSUE TITLE
Is the development of the extension has stopped?

### ISSUE THREAD

**Issue by hackyyy** [rainforestapp/tester-chrome-extension#39]
I see that the last commit of the extension is from 2 months ago, also the last news here https://portal.rainforestqa.com/ is very old.
So is the development of this extension terminated?

**Comment by pscohn** [comment]
@hackyyy Development hasn't stopped at all, but as you see in the issues page there are several bugs we're working on fixing. That code we're working on is not in the Chrome extension itself, but in the Rainforest code base, so you can't see that we're still working on it :P

There haven't been recent posts on the Portal because there haven't been any major features to announce recently, since the focus has been fixing things. Expect to see some more good things coming in the future, though.
