### ISSUE TITLE
No 10% daily bonus

### ISSUE THREAD

**Issue by irishclouds** [rainforestapp/tester-chrome-extension#390]
Yesterday i have finished 13 jobs, but i don't see any 10% bonus, same problem 2 days ago. Someone have the same problem?

**Comment by uqbiii** [comment]
Working fine for me, check if you received a notification similar to this one in your dashboard, or else check your email associated with RF account. If still nothing, you should file a ticket.
![screenshot 10](https://cloud.githubusercontent.com/assets/16700973/17696291/d9eeaa2a-63c6-11e6-9b94-6bc6e322c461.png)

**Comment by qpPykT** [comment]
@uqbiii 
So, and why you're post screenshot from 08/01-02/16 if right now 08/16/16.

@irishclouds 

> Yesterday i have finished 13 jobs, but i don't see any 10% bonus, same problem 2 days ago. Someone have the same problem?

You can see your payments bonus in last task what you have done yesterday. Bonus will be automatically added to the last completed task.

**Comment by uqbiii** [comment]
@qpPykT  Just because i saved it a few days ago, it was my best so i saved that, as i don't open notification for a day until the days ends, it is the easiest way to check how much HITs i completed for that day, otherwise i will post the latest one, if you want to check new one, i will post that, let me know then i will open my notifications!!!.

**Comment by nerdatwork** [comment]
@irishclouds What @qpPykT says is correct. Have you checked your history yet. Can you confirm whether the bonus was given to you ?
