### ISSUE TITLE
Unfair test training  x2 rejections.. @pscohn help please

### ISSUE THREAD

**Issue by josejecr97** [rainforestapp/tester-chrome-extension#417]
https://i.gyazo.com/a27a18b422dad854363da208741d04b3.png

https://i.gyazo.com/752c6e105e6e7eda04debe9aa2384b7d.png

https://i.gyazo.com/1f7dd94a0adeca83ec41d7be657a27b6.png

i still dont know why im still getting training jobs, its really unfair, i've doed like 50 now... and they are still coming .. what is wrong????

**Comment by eudy66** [comment]
friend if I miss over 50 and likewise I keep getting the same as training and worse has happened to me also what you because I have thrown three bad because of that failure ... I hope can be fixed. good day.

**Comment by GersonTavare** [comment]
I receive 6 - ridiculous - rejections in almost 100 training hits. And I'm receiving training until now.

Rainforest just have change for the worse

**Comment by josejecr97** [comment]
http://oi63.tinypic.com/2z8w50l.jpg @pscohn @jbarber 
https://gyazo.com/4ce9e91bf58718f0590226c20729530a
https://i.gyazo.com/107fe48d4a23ed83aa93a85913f3b142.png

there is a prove that i've getting unfair rejections.. please fix this ..

**Comment by Yhenko** [comment]
Agree, 1 unfair rejection with the same Feedback "Everything on this page was correct - you should not have reported a bug."

**Comment by nerdatwork** [comment]
@josejecr97 Post a screenshot of the rejections page in your profile. The image shows only the last step, it might be possible you answered incorrectly for the middle test questions.

**Comment by uangonline** [comment]
@josejecr97 Yes, i can see that unfair correction (from the second link you gave). If the first answer is YES and marked as correct, than your last answer ("NO") should be correct since it have different password. Hope RF support team can help you.

**Comment by maciejgryka** [comment]
@josejecr97 I've looked at the jobs you pasted and the training system is working fine: you have made some mistakes and your work was rejected (which is exactly what training is for!). In the first job you (8154117) it looks like you mis-pasted or mistyped something. In the second one (8160437) you have completed the signup more than once within the same job.

We do not only check your answers, but also that you complete the entire job exactly according to instructions, exactly in the order you are asked to do them and at the right time. It is extremely important to our customers that all instructions are followed to the letter, which is why we are very strict about this.

**Comment by josejecr97** [comment]
https://i.gyazo.com/107fe48d4a23ed83aa93a85913f3b142.png
in this image is clear that the passwords are diferent ..
https://i.gyazo.com/4ce9e91bf58718f0590226c20729530a.png
and still got this.

Hmm, okey, but i still thinking that i did it right , it did jobs really carefully and i've been taking screen of all of them to post if i find something unfair. 

thanks for help btw. ill take care

**Comment by nerdatwork** [comment]
@josejecr97 Since you got a response up to your satisfaction you can close this thread.

**Comment by Electroglitch** [comment]
Can i just point a little overlooked flaw in this,
i remember doing training tasks about 2-3 month ago
and when i was doing one training task terminal was having problems with taking screenshot(failed to take a screenshot message over and over) at the last step 
so i had to restart the task
and no matter if i did everything right i got 1 rejection because of what maciejgryka  wrote "(8160437) you have completed the signup more than once within the same job."
thankfully i had problem with terminal just once and it was my only rejection in more than year and a half :)
