### ISSUE TITLE
training ???

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#418]
![training](https://cloud.githubusercontent.com/assets/19192312/17954315/1f60c372-6a48-11e6-8c22-c1f5f0d049b5.jpg)

really ? o.o

**Comment by kaytsu** [comment]
"Training Jobs 2016-08-24 13:02:25 UTC, Kristen Hohenstein
Hello, testers! We have various ways of evaluating your performance. Since yesterday we’ve increased our quality threshold, which means that being given paid jobs is more difficult than previously. If we see your performance isn't meeting our expectations, you will only be given training jobs until we're sure your work can be trusted (this may take a long time, depending on your history!) Even when we trust your work again, we will continue monitoring your submissions and might put you back in the training sandbox if we detect poor performance. A very small percentage of our testers fall into this category, so as long as you keep up the good work, you have nothing to worry about!" on the front page of the portal.

**Comment by nerdatwork** [comment]
@zfonck123 There are already many threads dealing with same topic. I recommend reading the old threads and post replies in the topic that concerns you instead of opening up a new thread. Please close this thread.
