### ISSUE TITLE
Real jobs and training real jobs and training ???

### ISSUE THREAD

**Issue by zfonck123** [rainforestapp/tester-chrome-extension#445]
what happen ? 
![image](https://cloud.githubusercontent.com/assets/19192312/18069924/58258840-6e18-11e6-9509-fb5a5fa4decf.png)

**Comment by JrRandy** [comment]
yeah, I have been getting the same.  Few real, few training, few real, few training.

**Comment by josejecr97** [comment]
#439

**Comment by JrRandy** [comment]
@josejecr97 I dont think this has any relation to "Unfair rejections" thread you linked.

**Comment by sweeneyapps** [comment]
nobody deserve this.     I have done like 14 training jobs after doing nothing wrong.   No rejections even no rejections on training jobs task.    So I decided to turn off my chrome extension for the day and hopefully by tomorrow, I am getting paid job.    Again, nobody deserve this at all.   Also in USA, we do pay our workers on their training day.    So Rainforest needs to go back to the drawing board and figure out to do this the legal way.   And compensation all of us.   Thank you for ur time to hear me out.

**Comment by JPierreS** [comment]
@sweeneyapps :  In an ideal world yes - but in a world of abuse and cheaters, sometimes harsh measures need to be taken.  I can completely understand Rainforest's decision NOT to pay those trainers.   In regards to the OP, the issue yesterday was due to a bug that caused assignment of  training jobs even after receiving the training complete and passed.   These are training hits that anybody is subject to from new to older testers and is not the same thing as training limbo where testers are subject to long periods of training due to consistently bad work.  : ) So you can imagine if the training was paid, the bad worker being retrained and having to do 50-100 or more in a row would be so happy they are being paid and they would rather get those 50-100 training jobs than the rubbish the rest of us get mainly badly written tests and such.  So YES all training SHOULD be paid.....but on the flip side those who are working poorly should not have an incentive to do so :)

As far as legality, if that were really the case then CF and all crowd sourcing would be shut down - Remember that UPWORK minimum page wage allows for $3 lol  far below US minimum wage :D  So since we are not "employees" I guess this might not apply.  Are us GOOD workers getting paid what we deserve and our true value, NO ! But CrowdSourcing tasks are free market, people can decide to work or stop working - Unfortunately at the moment there are not much worthy tasks to work from and RF still shines compared to other tasks so people should be a little more careful and preserve this task :dancer: 

@zfonck123 

The alternating real jobs vs. training was a bug, since then training jobs were disabled for now.

Keep in mind at any point in your testing career you will be subject to those random training hits.

As far as training limbo long overdue ! But for the love for God, get the training material fixed and 100% acurate, as it is right now SOME of the training hits are poorly worded and flawed.  Many of us experienced testers were rejected, we can't all be that dumb.  :)

Cheers

**Comment by maciejgryka** [comment]
Hey - we've just posted an update to our news portal about yesterday's training jobs: https://portal.rainforestqa.com/.

**Comment by sweeneyapps** [comment]
@maciejgryka  Since it's your "oops bug",   will you pay us for all of the training lessons for those who are not really inside the bad tester's sandbox?   Keep in mind..  some of testers are living in country where their pay are 1 dollar per hour.   Rainforest is their living income and they are loyal to you...  They need to provide for their family.  A day loss isn't good.

**Comment by zfonck123** [comment]
in my country the salary of 30 days = 22usd  :(
