### ISSUE TITLE
I can't start 

### ISSUE THREAD

**Issue by javiraro** [rainforestapp/tester-chrome-extension#450]
I sent yesterday a ticket to try to solve my problem but I'm still waiting so I open this topic. I started too late like 2 years later doing rainforest account and everything. I did on sunday, signed every qualifications and staying with rainforest chrome extension opened for 8+ hours a day opened and always says NO (so I don't have any task to do) and yes, I'm always looking if it changes to OFF if you're asking yourselves. Is this any bug? How can I start? thanks.

**Comment by nerdatwork** [comment]
Even if you got a job you will NOT be paid since you came back after 2 years. You should have done a task when the new testers were being recruited. Still try to do a job and check your profile where it shows any payment confirmation. A new job loads when the extension turns to **YES** so as long as it's NO you are good to go.

**Comment by javiraro** [comment]
Do you know when they do tasks for new testers?

**Comment by sweeneyapps** [comment]
@javiraro There's no answer to your question but if Rainforest felt that they need more testers.   That is when demand is high.    Just like economy..    high demand = more workers.     Right now, there are MORE MORE worker than the demand itself.     It could stay closed for long time until demand is met because too many testers in the system right now.
