### ISSUE TITLE
ABOUT CHANG TH ID WORKED 

### ISSUE THREAD

**Issue by MOHAMMEDAMRANI82** [rainforestapp/tester-chrome-extension#451]
MESSAGE FOR Me to rainforest team : 
Aujourd'hui à 00h09
"please change my id to : 38715621"

 Answer : 
Rainforest Support
Today at 05:46
Hello,
If you completed "Test Applications for Rainforest QA" while this option was still available and clicked "Claim it", check your CrowdFlower notifications and add your email address using the claim link in the instructions. If you clicked "Claim it" but didn't receive a notification, you can add your email to the account by installing the chrome extension and adding your email address after completing a job. The email address used on your new profile must be different from the email address used on a previous Rainforest profile you may have had, otherwise this will cause some account issues (e.g. signing you into your old account). It's important to note that 1) You can only use one Rainforest profile. If you claim a new profile, you can no longer use your old Rainforest profile, and 2) If your Rainforest profile has been blocked, you are prohibited from ever creating another profile. Have a great day!
Regards,

Rainforest Support
rainforestqa.com

please comment this answer

**Comment by nerdatwork** [comment]
Rainforest **does not** change worker ids.

**Comment by uqbiii** [comment]
If they start changing ID's then a new business starts of buying and selling, people who have profiles will sell them to even those who don't have any Level badges, or mturk qualifications.

**Comment by JPierreS** [comment]
Actually there are genuine reasons why people want to change IDs. If you stop working in one given channel you might want to resume work in another.  Sadly, the way CrowdFlower is set up is that you get a different contributor ID on each channel you work on, and Rainforest has no way of identifying you by your CrowdFlower ACCOUNT - instead, they can only identify you through whatever contributor ID you are working from, from the channel you signed up with.

The solution to this would be a unified account system, where the workerID would represent a Rainforest account ID instead of a CF ID.  This Rainforest ID would be the same whether you work from CF Elite, ClixSense, Neobux or any other channels.  A user could configure which channel to get paid to through their rainforest profile, this would solve once and for all BAN evasion and use of multiple RF profiles.  

Hopefully this can be considered  as with the current system, when registrations were open a user could technically have up to 25 Rainforest accounts (worst case scenario as a user could sign up with 25 channels and work on a RF task on each)

Current situation right now it is not possible to change an ID or migrate account to another.

If not Rainforest, perhaps CrowdFlower could implement something to allow diverting one old channel to another (channel forwarding) - but very unlikely either company will implement this as this might not be on the top priority list.

**Comment by HW71** [comment]
Sorry @uqbiii - can you please explain a little bit more detailed where you see a problem with changing ID's? "Selling accounts"? Seriously?

The "only" problem I see is that for whatever reason RF deicded to identify a tester by his / her Crowdflower Contributor ID. Which (at least from my point of view) is the worst decision a company could take because of two reasons:

1. you make your own business / software architecture heavily dependent on a third party (in this case Crowdflower). Additionally they don't offer an independent payment option (like for example Paypal). So if CF goes out of business for whatever reasons RF will be in big trouble.

2. there's no option for testers to choose to which PTC site / channel the "bonuses" should get paid. There are so many good reasons why a change of Contributor ID is indicated - but that's not possible if there's a 1:1 relationship between Contributor ID and RF account!
Actually a RF account should be uniquely identified by username. And not by a third party entity like CF Contributor ID! Such things should be an attribute / property of the account - but not be part of the key identifying an account.

If they want to prevent "selling" accounts then they should establish some kind of verification process. For example changing Contributor IDs should only be allowed if the "new" Contributor ID belongs to the same Crowdflower Profile / Crowdflower Account. That is: on my Crowdflower Profile page I see a list of all Channels and the related Contributor IDs. And a change of the Contributor ID used for RF should only be possible, if the new Contributor ID is in this list. Maybe CF currently doesn't offer an API for verifying this - but hey, they both reside in SF. It should be possible for them to sort this out ;-)

I'd even more appreciate if RF would offer an alternative payment option, but by the end of the day all these suggestions have one pre-requiste: get rid of this 1:1 relationship between RF account and CF Contributor ID.

**Comment by josejecr97** [comment]
@HW71  agree, i think the same .... many users are getting banned from cf and ptc sites, and they are unable to get their payments... 

who will send accounts of RF? its not logic , we can make allot of money working here

**Comment by josejecr97** [comment]
I'd even more appreciate if RF would offer an alternative payment option ... agree with that too, would be the best thing .

**Comment by uqbiii** [comment]
Currently i am also suspended from CrowdFlower and i don't want to work anymore with this unfair system where a third class author can suspend your 2 years old account, suppose i create a new account on CF and at that time rf also offers to change worker id's, what will i do in this case, of course i will change my previous id _(i have 4 ids related to rf, 1 claimed and three unclaimed, because when there was no extension, you can complete HITs from any channel you like and i completed HITs from 4 different channels but claimed only one)_  with the new one, don't you think it's a business, a pure fraud to earn money.
@JPierreS  @HW71 I also think the same way as you, i also want to be a part of system which is independent from other platforms especially from CF. I also agree to all the problems and suggestions you written there. I am still working on HITs without any money because it's the best way to spend my time. CF is very clever and they created a system where their workers cannot be unite, otherwise they will behave nicely when we demand something.

**Comment by isabel40** [comment]
I was working for RF in a PTC that it suspended my account. I have active my RF account, but I´m not working because I lose the payment. Actually, I´m working in another PTC that have CF;  there is any way to change the RF payments to this new PTC?  I sent a ticket to RF one week ago, but I haven´t answer :( Sorry if I don´t explain well, Thank you for your help

**Comment by uqbiii** [comment]
Sorry Dear, but currently you cannot change your worker id, and there are lots of people facing the same problem, i hope their will be a good solution from RainforestQA.

**Comment by nerdatwork** [comment]
@isabel40 Rainforest does not change worker ids and payment and/or stats from one id cannot be transferred into another id. If and when Rainforest opens it's doors to new testers you can try to claim a new profile but till then I am really sorry there is nothing can be done.

_Thank you for being part of **Rainforest**._

**Comment by HW71** [comment]
@nerdatwork 
Since you repeatedly stated "RF does not change worker id and **cannot** forward payment / stats to another id" it would be really interesting for all impacted testers, what the technical reason behind this decision is. As I already pointed out earlier at least from my point of view this is an architectural design flaw on Rainforest end and of course it should be possible to use a different worker ID - **especially if we verified our RF account by SMS**! So simply insisting "It's not our fault - we won't help you" sounds harsh!

"Of course" RF seems to argue that this is a Crowdflower issue - and CF argues, it's a RF bug. So by the end of the day valuable Rainforest testers are the folks suffering from this! 

And please remember: Aside from cases where PTC get blocked (maybe for good reasons) you will also see cases in future where Crowdflower Accounts can not be used any longer because the PTC site itself gets out of business.

**Comment by nerdatwork** [comment]
@HW71 Please read this: [Can I change CrowdFlower id used for payment](https://github.com/rainforestapp/tester-chrome-extension/wiki/Frequently-Asked-Questions#can-i-change-my-crowdflower-id-used-for-payment)

**Comment by HW71** [comment]
@nerdatwork 
Is my English that bad?

**Comment by nerdatwork** [comment]
Nope but I know someone who can give you a very detailed reply ;)

**Comment by HW71** [comment]
OK, and this "someone" can be found in the FAQ, or what? Sorry, I don't get the point why you initially linked to the FAQ ... :-( Anyhow: I'm really glad to hear that you know someone who could give a detailed reply :-) - but this doesn't help the rest of us, right? And if I have a look through the tickets opened recently there are a lot of similar issues related to this (as "expected" some weeks ago)!

Again: the easiest thing for RF to solve ALL of these problems would be to offer additional payment options - and maybe to make "Account Verification" by SMS mandatory if we want to get paid by for example Paypal.
Then we could keep the architecture / dependency on CrowdFlower "as is" (if there are good reasons to o so - hope to read some words from your "someone" regarding this, though ;-)  ), but all testers stuck in this weird CrowdFlower-pitfall could get paid for their (hopefully) good work they do!

**Comment by helloworld111gh** [comment]
As a former Crowd flower Task Author, I can tell you it is impossible to
send a contributor ID bonuses without first having that ID do one of your
task on the task list.
It is not a problem on RF's end, it is a problem on CF's.

Although yes, adding PayPal would be the best fix to this issue, and it
would also save Rainforest money (Crowd flower charges an additional 30%
fee on all bonuses, PayPal charges ~2%.)

**Comment by JPierreS** [comment]
@helloworld111gh Exactly, - however RF can set up a special task protect it with password and target it for the specific contributor ID of the new channel (I had a task author do this for me once) and some person ended up cheating and doing it on my behalf :( So ideally would be requester sending a direct link to claim new profile.

The main issue is CF - they CAN fix this on their end to allow forwarding unused Contributor IDs to new ones.  If Rainforest had a way to identify workers by their CF account problem would be resolved, but they can only see you through your channel ID and not your unique CF account.

CF is not addressing this issue due to the fact the majority of the tasks are hosted through CF.  Rainforest is a rare exception of externally run tasks, so they (CF) might not see the use of this so RF is left to pick up the pieces.

@helloworld111gh  30% ???  Wasn't it 10% before ??? FH ! it's almost as bad as mTurk.
Yeah RF might save on fees, but setting the whole thing up to allow direct payment is a BIG thing
if it were not they would have done it ages ago and not need to post the jobs on turk or CF. :dancer: 
Offering this task directly through RF would mean better control over multi accounts, cheaters, etc, along with a verification system and would also allow external crowds other than CF, perhaps even more experienced, trustworthy crowd :dancer: 
Maybe when RF keeps growing eventually they might do this, as it is right now if a tester has 50,000-100,000 hits completed and suddenly the channel goes tits up then the worker's career is done :(  Hopefully CF can do something about this quick.

**Comment by helloworld111gh** [comment]
I don't think CF will want be less restrictive with IDs, due to the "You
can only do this task from one ID" shenanigans, even if the task was
available affected workers may not be able to claim a new profile because
they can't access the job from their new ID
Although an easier way to fix it on CFs end is to use that "Preferred
Channel" setting and have all bonuses sent to the preferred channel. That
way it doesn't matter if your old ID went poof, you can just change the
preferred channel.
And I checked, the fee is actually 20%, not 30%.

**Comment by isabel40** [comment]
Thank for your help I will be waiting for a new oportuniti
