### ISSUE TITLE
Linking Rainforest Account With Another Channel

### ISSUE THREAD

**Issue by samizle** [rainforestapp/tester-chrome-extension#461]
Hello,

I have recently had my Neobux account suspended because I mistakenly used a proxy without even accessing the site. I do not really know how it detected my location change, maybe through the Neobux extension installed on my browser. 

Briefly, I hope I get it reopened, if not, is it possible to link my rainforest account to another channel like Clixsense or with another new Neobux account?
What would be the solution in this situation, guys? Thank you!

**Comment by nerdatwork** [comment]
It is sad to know that your account is suspended @ Neobux but Rainforest **DOES NOT** link accounts or stats or payment from one id to another. The only real hope is if Neobux reopens your account else you have to wait till Rainforest opens it's doors for new testers for you to be able to claim a new profile.

**Comment by JPierreS** [comment]
@samizle  I'm sorry to learn that you got banned from NEOBUX, but what happened is that you got detected through the neobux extension.  Keep in mind that the use of PROXY is prohibited on legit GPT / PTC sites as well.  Obviously you can argue that this was an honest mistake and that you did not click any ads through the use of the proxy.   Send a request to support and be super polite about it and they might forgive you this time (at their discretion of course) as they enforce the TOS by the book.
These measures are in place to protect advertisers and offer providers from fraud.

As Rainforest goes, unfortunately they cannot change your payment channel.  This whole situation is CrowdFlower's fault unfortunately, as Rainforest has no way of identifying you through your CF Account.  They can only see you through your channel ID, and each channel ID that you work from is considered a unique RF account.    CrowdFlower could make some changes on their side to allow this to happen, without RF making any changes, (such as channel forwarding, etc.) and of course CF would do it, but due to the abuse and fraud on their platform, I don't think they will do this anytime soon :(

The only way is to claim a profile through a new channel once registration opens again (if it opens again) ;-)

Your best bet is to get your neobux account reinstated.  If you do, remember not to make use of proxies whilst using PTC/GPT or their respective extensions.  If there was a legit reason why you needed to use a proxy, you can use this as an argument, and maybe they might reinstate you.  Neobux has a history of reinstating suspended members, depending on the violation so good luck, and I hope it works out for you.

**Comment by samizle** [comment]
Thank you @nerdatwork for your support. 

@JPierreS thank you very much for this detailed explanation. Guys, trust me I did not use a proxy to fraud Neobux and I made sure I closed the Neobux window before using it, but I forgot to deactivate the Neobux extension which, certainly, was the one detecting my location change.

 It is so stupid the reason behind my using a proxy, but here it is: I used a proxy to change my location to check the internet speed. I also used it to change my location to Indonesia so that I could change my facebook full name as a first name only,,,  just nonsense what I have done I know. 

I wrote the support a polite formal email and I explained to them. I already have my Crowdflower linked to my Clixsense; so if ever I fail to have my account restored (even without the $55 balance in it, which will be usually reset to zero as a penalty), I hope Rainforest help me switch my payment or channel ID to Clixsense as shown in the screenshot below. I do not want to lose my Rainforest account as well :(

 I am not sure if I open new Neobux account, I will not be facing a problem with my our payment processors registered (Neteller + Payza). Just keeping my fingers crossed till they reply. It's really driving me insane
![rainforestqa](https://cloud.githubusercontent.com/assets/21021455/18227282/1c44687a-7217-11e6-9dab-1a6db1f91132.png)
 the whole situation especially when it truly is not my intention to fraud the system behind having a proxy. I know what it is, but that's it. What's done is done.

**Comment by JPierreS** [comment]
@samizle Ok in your case you clearly did not intend to cheat advertisers therefore I think this was an honest mistake.  Whatever you do, do not create a new neobux account, you will not get the same contributor ID you had before.
Try contacting their support through support@neobux.com if that does not work
use tickets@neobux.com and explain what happened.

You received an automatic suspension, so hopefully they would give you a chance and re-instate you.

If the support/tickets e-mail does not work and you do decide to create a new account do not click ANY ads or link any CF account to it, only use it to send a support ticket, nothing else.  If you create a new account to do anything else other than sending support,, then odds will not be in your favour :)

**Comment by samizle** [comment]
@JPierreS Thank you very much for your reply and being helpful to me. I have good news. Yes, I got it back. I checked my email box but ain't no reply. I head directly to the site and I found it running back to normal. And I could also cash out successfully. Thank God!

There is truly nothing more I was sad about is losing my Rainforest account than losing Neobux with the cash inside. I extremely love what I am doing with Rainforest, out of passion. Thankfully, everything back on track now and we get back to work. ☺

![nebuxpayoutneteller](https://cloud.githubusercontent.com/assets/21021455/18230286/1a5e6872-728e-11e6-9084-332d60091bd3.png)

**Comment by nerdatwork** [comment]
@samizle I am very happy that you got your account back. It is good to know that honest members are getting the right support they need. Learn from these mistakes and help others when they face issues. Let's be an awesome community of testers working towards providing quality results.

**_Keep the faith and Happy Testing_**

**Comment by samizle** [comment]
@nerdatwork I am truly glad to have my account back and delighted to be a part of this supportive and helpful community. Thank you for your assistance, I appreciate it!

Keep up the good work and happy testing! :)
