### ISSUE TITLE
Clixsense problem.

### ISSUE THREAD

**Issue by hagenes** [rainforestapp/tester-chrome-extension#463]
What should we do? What if he does not recover ?

**Comment by runna17** [comment]
Instead ClixSense opens gay porn site.

**Comment by HW71** [comment]
Wow! Just double-checked - happens for me, too!
Now [my request for having additional payout options](https://github.com/rainforestapp/tester-chrome-extension/issues/451#issuecomment-244594788) (like Paypal) gets even more important! Didn't thought that this could happen to big PTC sites like ClixSense, but anyways. Keeping fingers crossed that this gets fixed by ClixSense, soon!

**Comment by A1xx** [comment]
Do anybody know is there any way to change worker ID? I work on CrowdFlower with clixsense and neobux, All payments from rainforest go to clixsense . Is there anyway to change it on neobux or other ptc? Or what shoud we do if clixsense will not work again.

**Comment by HW71** [comment]
@A1xx Well, as you read in the thread I linked in my post above there's on ongoing discussion regarding "Change of worker ID".

Unfortunately the CURRENT situation is: Rainforest will not offer the possibility to change the Crowdflower Contributor ID because of a unlucky design decision taken most probably early in the beginning. Point is: Rainforest uses the Crowdflower workder ID to uniquely identify a Rainfores account.

This is the reason why I'm "begging" Rainforest for weeks to offer alternative payment options, like for example Paypal in order to avoid situations like we see now!

I understand this would be coding effort on Rainforest side, but in the long run this would be best for BOTH Rainforest and testers!

**Comment by A1xx** [comment]
@HW71 Thanks for reply. So, right now I can't work with RF anymore( I hope ClixSense will recower

**Comment by susgar77** [comment]
I'm in the same situation, and very terrified of what might happen. I do not understand why not let us change PTC.

**Comment by HW71** [comment]
@A1xx You're welcome... :-) Actually you should still be able to work on Rainforest tasks, right? Assuming you use the Chrome extension you would still get HITs and can work on them. And the bonuses should get forwarded via Crowdflower to ClixSense. Of course the payout from ClixSense is a bit uncertain right now, but if we assume that it "just" a hack and ClixSense is still in business (what I definitely hope) then the only drawback right now is, that you can't trigger payments from ClixSense... But, well... That's how the Payment workflow currently looks like... :-(

**Comment by HW71** [comment]
@susgar77 As mentioned in several other places it's not that easy: I totally second the view of Rainforest that changing this would have MAJOR impact on ther side, because as of new every Rainforest account is directly linked to a Crowdflower Contributor ID.
What does that mean: if they would allow us to change our Contributor ID then we would get a NEW Rainforest account and loose our pending payments + additionally our "track" history.

The solution to that would be two options:

1. get rid of this 1:1 relationship between Contributor ID and Rainforest account. Personally I'd suggest this anyways, because such a dependency of Rainforest account to an external company like Crowdflower is ALWAYS a bad decision. What happens for example, if Crowdflower gets bankrupt?

2. Offer payment options independent of Crowdflower, for example Paypal, Netteller, Whatever...
By doing so Rainforest could stick with their beloved Crowdflower :-)But we as testers could get paid independent of any PTC, GPT side - and independent of Crowdflower!

**Comment by nerdatwork** [comment]
Clixsense is an old trusted site and they take backup of their site on regular basis. As soon as they open their offices they will take action to restore the site like any other business will do. 

@HW71 You know all the answers yet you look clueless.
What you suggest is 100% correct and yes there should be a way to get independent payments directly from Rainforest but since Rainforest has used Crowdflower to get the testers they were not aware of the issues we testers face. Since having another way to pay testers and adding new "features" would involve a total redesign of their code; it is not considered currently. 

Maybe some day it will be all fixed without any error messages and testers getting paid directly to their payment processors without involving PTCs or Crowdflower.

**Comment by EricBen** [comment]
Hello Everyone, first let me apologize for the issues today. Over the last several weeks we have been the target of a hacker who I believe first created the bot csadviewer and then moved on to submitting ads that when a viewer opened an attachment that popped up they got infected and their PC was compromised. Today, this hacker changed our DNS to a wonderful gay porn site. They removed our websites and email and of course with it being Sunday its hard to get any support. My phone has been ringing off the hook and my email blowing up. Please do not call or write in. We're definitely aware of this problem.

PLEASE NOTE!!!!!

The ClixSense servers were not hacked and all of our servers are still intact and your account information was not effected. As I said above, its a DNS hack. It may take a bit for the site to come back online due to propagation but it will be back as soon as possible. I have a close friend who works with the FBI Cyber Crimes who I will reach out to later today and let them know as we're going to open an investigation on this.

Again, I am sorry this happened and it's certainly not the way I planned to start my Sunday.

Thanks
Jim Grago
ClixSense.com

**Comment by A1xx** [comment]
@EricBen It's a great news. Thank you. I hope Jim can handle it in short time.

**Comment by nerdatwork** [comment]
@EricBen Where did you see this originally ?

**Comment by HW71** [comment]
The statement from Jim can be found here:
http://www.emoneyspace.com/forum/index.php/topic,413038.msg3874504.html

**Comment by susgar77** [comment]
My question is, if CrowdFlower offers us the opportunity to do their tasks
 with different ID according to the page for that work, why can not associate other of these IDs to account Rainforest and receive payments on the other page?
Would continue working with CF and RF also

![sin titulo](https://cloud.githubusercontent.com/assets/21985504/18231295/92adf75c-72b6-11e6-907d-fe4c18122538.png)

**Comment by susgar77** [comment]
My question is, if CrowdFlower offers us the opportunity to do their homework with different ID according to the page for that work, why can not associate other of these IDs to account Rainforest and receive payments on the other page?
Would continue working with CF and RF also


![sin titulo](https://cloud.githubusercontent.com/assets/21985504/18231299/bdbf4414-72b6-11e6-99d7-d4f8188ccc5d.png)

**Comment by HW71** [comment]
@susgar77 
Well, as mentioned above: there's a 1:1 relationship between your Crowdflower Contributor ID with a Rainforest ID!

To explain it in a different way:
let's assume you have three Corwdflower Contributor ID: 
100 - ClixSense
101 - NeoBux and 
102 - ProBux

Let's assume further: When you initially created your Rainforest Account you did that using ClixSense. So your current Rainforest Account has a "hard link" to Contributor ID 100 - which is ClixSense!

CrowdFlower (100) <========> Rainforest (susgar77)

Now if you would be able to change your Contributor ID of your Rainforest account to 101 (Neobux) then this would end up in a totally *new* Rainforest Account! So by the end of the day it would look like the following:

CrowdFlower (100) <========> Rainforest (susgar77)
CrowdFlower (101) <========> Rainforest (new, vanilly account)

**Comment by nerdatwork** [comment]
@HW71 Is 1001% correct. Also you can use 101 **only if** you did a job with 101 at least once only then you can start using it as your second id since 100 might be suspended/closed/banned.

**Comment by susgar77** [comment]
Very unfair .... because change does not involve changing the ID or the person who works, or CF.
Hopefully someone give us a solution, or many people leave their work here and CF :(

**Comment by HW71** [comment]
@susgar77 
Actually this has nothing to do with "fair" or "unfair". I'm really convinced that Rainforest initially was not aware of the side-effects this decision had, when they designed their application! So I don't think they're doing this to annoy us... :-)
BUT: on the other hand this was a dangerous take because THEIR accounts now have a strong dependency on Crowdflower, right? As mentioned earlier: what happens, if Crowdflower gets out of business? Unlikely? Not at all!

So by the end of the day it's not just unpleasant for us testers - it's also dangerous for Rainforest!

**Comment by HW71** [comment]
@nerdatwork
You wrote:
> Since having another way to pay testers and adding new "features" would involve a total redesign of their code;

No! A "total redesign" would **only** be necessary, if they really intend to get rid of the Contributor ID used to uniquely identify a Rainforest account! But if they'd decide (as a first step) to just offer an independent payment processor like Paypal then this would just be an additional *attribute* of their currently already existing Rainforest accounts!

To stick with the picture above:

Currently:

CrowdFlower (100) <========> Rainforest (HW71)

With a new attribute for "Payment processor":

CrowdFlower (100) <========> Rainforest (HW71) ==========> Payment Processor (Paypal)

They could keep the link the Crowndflower "as is" - and just offer an additional Payment processor to get paid! of course this would mean some coding, too (but they have good testers, right? ;-)  ) - but it would be way less effort then getting rid of Crowdflower completely!

Btw.: Thanks for calling me "clueless"! :-) Hope this is just a "saying" in English where you express your sympathy... ;-)

**Comment by roko777** [comment]
It's a great news. In the morning I was a little scared))) $ 300 is also money), I did not have time to withdraw their money.We can only hope and wait.

**Comment by sweeneyapps** [comment]
regarding paypal or another payment processor.    I know it does seems easy to implement payments via programming (API).   That is what they did w/ CF and mTurk.   But in RF's eyes, CF and mTurk are not a payment processor, they are only service who provide workers.   That's a relationship between (CF and mTurk) and RF.   That makes it easy for RF to just recruit workers and let those sites handle their ID and payment.

To shift away from those service sites,  RF will have to hire legal team to handle contracts between workers and RF.  It does involved USA law regarding taxes and identification process.  When that's done, then RF will have to have their engineering team to design a system to be added to the portal.rainforestqa.com.   It will be one of big project which RF doesn't have the resource for as of right now.  It will involves database work such as more deeper profile information including your personal data such as contracts, identification (tax id, state id, country id) which need to be secured 100%, then finally payment processor information.    Then figuring out the process involving RF and payment processor via API.   Also designing a policy to limit the flow of payment between payment processor and RF workers such as withdrawal from RF account to payment processor maybe possibility of setting min. $50 or monthly limit on how many workers can transfer their payment.   That's where database will be designed to handle how much workers earn and payment transfers.   Like I say earlier, they still need legal team to design process on creation of worker's account and their nationality since RF is an American company and they will have to figure out how to do business internationally.

**Comment by hagenes** [comment]
I just asked about ClixSense. some workers may already come , but I again naked priests , and I can not see whether the money comes from the tropical forests .

**Comment by hagenes** [comment]
Steps have already - I see Google , not hairy

**Comment by JPierreS** [comment]
In regards to ClixSense the site was not hacked - all user accounts are safe !  What happened is that the DNS account settings got changed, to redirect to another site of a different "industry".
The owner is aware of this and will take necessary action towards the person(s) responsible.
Meanwhile for some people the site is back online, for others it may not be, as it depends on your ISP and how fast they update.  It can take from several hours to worst cases days.

If you still cannot access ClixSense you may revert to using google's DNS servers instead
by changing some settings.   Access your network, open network and sharing center,
change adapter settings, double click on the active connection, properties, from the network tab double click on the "internet protocol version 4 (TCP/IPv4)", from the general tab locate select "use the following DNS server addresses " and use 8.8.8.8 and 8.8.4.4 as shown here
![dnschange](https://cloud.githubusercontent.com/assets/7692133/18237774/718f387c-7303-11e6-933a-74bd0828f9e9.jpg)

Clear your browser cache and reload site, it should work now.

Meanwhile rest assured, you will still get paid to whatever jobs you complete on CrowdFlower and Rainforest, even if the site is offline.

**Comment by hagenes** [comment]
JPierreS, Many thanks for your valuable information . Set Provider my husband in the evening ( if I do it myself - mad ) ) ) , but the fact that the revenue streams - confirmed my REFER

**Comment by JPierreS** [comment]
Oh right I forgot to mention there, in reference to your previous posts, yes not to worry mate, the money will come from the tropical forests, but no naked priests please, none of that :))  Cheers ! ;-)

**Comment by euparkeria** [comment]
"With ClixSense trouble occurs" Are you Yoda? 
Rainforest needs to implement a language proficiency exam for all testers.

**Comment by runna17** [comment]
It seems that the hacked and accounts. For many people the balance zeroed.

**Comment by HW71** [comment]
@sweeneyapps 
First of all thanks for bringing this legal / tax stuff on the table. Actually I'm not quite sure if they really need to do that.

You wrote:

> To shift away from those service sites, RF will have to hire legal team to handle 
> contracts between workers and RF. It does involved USA law regarding taxes
> and identification process. 
 
What if RF continues to use the original ContributorID to uniquely identify a tester in their (RF) system - but instead of offering Paypal / other payment options they would allow to configure an _additional_ ContributorID for the actual bonus payment through CrowdFlower?

This would look like the following:
Old CrowdFlower ContributorID for abandoned N***x account is 100. This is still used to reference my active Rainforest Account HW71 - but bonus payment is done to my current C***e ContributorID 101, which I can configure in my RF profile:
   
CrowdFlower (100) <========> Rainforest (HW71) ===== bonus ====> CrowdFlower (101)

IIRC there were some concerns regarding "Selling of accounts" - but to be honest I didn't fully got this argument. Maybe this is a valid and major issue? But anyways: by using that approach (maybe with some additional restrictions) RF would still avoid all this legal stuff, right?

Just an idea to get this sorted out, because as we can see in latest September AMA this impacts a lot of people. And with latest ClixSense data breach this gets more and more important, because even large PTC / GPT sites could get busted quickly.

**Comment by HW71** [comment]
Not quite sure if everyone here in the thread follows the regular AMA questions and answers, so this is just for reference:
In the latest AMA session there were once again a lot of questions regarding alternative payment options and some interesting answers from @kristen-allie et al.

The document can be found here:
https://paper.dropbox.com/doc/September-AMA-Shared-with-testers-rHyakRpZEZ1P0i3029ews

Some answers worth to note include:

> We are aware of the many complaints with CF and hope to offer a better payment solution 
> in the future, but we have other goals we must meet before taking this big task on. Of course
> if something happened where CrowdFlower no longer exists, or makes policies that keeps us
> from working with them, we will pay you another way whether it be through another platform,
> or our own.

So this answer refers to the case if CrowdFlower would shut-down business. But the more important thing is, that single PTC sites (like ClixSense) could should-down. And this would lead exactly to the problem outlined in the picture above: we have an abandoned CrowdFlower ContributorID which is linked to a single RF account, we can't receive bonus payments to that any more.

Actually the next question in the AMA seems to deal with that stuation:

> Dear Rainforest, please consider a solution in regards to the changing of worker IDs. Many
> contributors would like to change their CrowdFlower channels and currently it is not possible
> to earn from Rainforest jobs through the new channels. I am aware that Rainforest can only
> identify a worker through their contributor ID and NOT their CrowdFLower Account name,
> however this can be a major problem if a particular channel goes belly up, which can happen,
> and this would leave a tester without Rainforest earnings.

The answer to that request (possibility to change the ContributorID) looks like the following:

> This is something RF is actively thinking about. We hope to make this better for you all in the future!

So maybe "changing" would not be necessary - but adding an additional ContributorID used to sent the bonus payments to could do the trick without major efforts...

Keeping fingers crossed... :-)

**Comment by sweeneyapps** [comment]
@HW71 yeah I was only talking about what IF RainforestQA decided to pay testers directly via paypal, amazon payments, etc.   I do agree that it's something RF needs to work on.. by working with CrowdFlower for better solution on ContributorID.

**Comment by JPierreS** [comment]
Changing contributor IDs is one thing, but they would have to transfer your account stats as well, to avoid starting from 0.

As far as shutting down, an individual channel has more chance of shutting down than CrowdFlower.  Mind you, ClixSense and Neobux are 2 long standing and well established sites that have existed for many years and run by people who know what they are doing.  It is the smaller PTC/GPT to watch out for, as some operate as ponzi schemes (revshare or referral system etc, where on these sites CF was also available, i.e PROBUX).  I would not worry much about Clixsense or Neobux these sites are worth gold - if anything they would likely get sold to new owners and not actually shut down.   As far as ClixSense they are growing and doing well.

As far as CrowdFlower, unlikely they will shut down - but one has to be ready for the worst case scenario or if they change policies in regards to external payments or the relation with RF.

**Comment by HW71** [comment]
@sweeneyapps 
Thanks for the clarification. Well, actuallly I think both sides (CF _and_ RF) could help to resolve this. CrowdFlower for example has this "Preferred Channel" attribute, which can be set by us for exactly one ContributorID. So maybe they could implement some logic like 

_"If bonus payments arrive for an abandonned PTC / GPT channel then automatically forward these payments to the 'preferred' channel."_

Or they could expose this "Preferred" channel to their API so customers like Rainforest could use this as "backup" payment channel (just taking a stab in the dark, of course). Maybe RF / @kristen-allie could talk to CrowdFlower and check the possibilities for a CF-based solution?

@JPierreS 
Yes, of course. Transferring stats and pending payments should be moved then, too. Alternatively: Check with Crowdflower for an "internal" solution (see comment to @sweeneyapps ).

And I second your point: Both NeoBux and ClixSense are in the business for quite some time so one could assume them to be "save". But considering the recent data breach at ClixSense (and the revealed details about the hack) there _might_ be some good reasons to at least question the usage of ClixSense in future.
Or see for example @Remesa having exactly the same problem like me ( => issue #663 ): abandon a PTC account due to personal reasons, e.g. don't log-in for quite some time (there are countless private reasons for that - including intentional deleting of a specific PTC account) - and by the end of the day payments show up in your RF profile and history - but they are "pending"...

As mentioned above there are several ways on how to get rid of this "trap" of not getting payed due to a CrowdFlower payment channel issue. I already opened a CF ticket several weeks ago, but the motivation to deal with that problem seems to be ... well, "limited"... :-/

**Comment by Remesa** [comment]
Lets see if they can solve this in the future

**Comment by famfanoz** [comment]
Hello, are you looking extra money? i recommend Clixsense. Free to sign up by clicking below link.

http://www.clixsense.com/?8172285
