### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by flasthem** [rainforestapp/tester-chrome-extension#464]
Hello,since yesterday im getting training jobs and i did 10+ but there is a job that is about a refrigerator instructions that is bugged and i got 2 unfair rejections the 2 times i did it,the bad thing is im getting this job all the time i turn on the rf addon and i cant do it because if i do it i get more rejections.Please i neeed help!

**Comment by JPierreS** [comment]
If you are absolutely sure that the training job is unfair, note the JOB ID and contact Rainforest support - but first, make sure you followed the instructions exactly.  The thing with training hits is that not only do they have an expected answer, but that alone is not enough - they also look for the proper interactions inside the terminal, so clicking the right answer alone is not enough.   Given this, it is very important that if you make a mistake (example clicking the wrong button) that you cannot correct yourself, you must restart the JOB and start over, or you will still get a rejection.   For example if an instruction asks you to download a file then upload it, but you accidentally click the upload button first, you cannot just cancel and download the file, it will detect wrong interaction and reject you.

I do agree that some training hits have poor wording that can be ambiguous, however, I not all of them.  Some are tricky and intentionally difficult and requires good observation.

One thing when training someone they should be told what they did wrong in hopes of correcting themselves, something not done here, which is bad IMHO.  I believe RF should set dynamic training that change over time, and provide proper feedback on what went wrong, because unless you know what you did wrong you will get the same rejections over and over - the fact training hits would have some dynamic / random elements would also make it harder for answers sheets to circulate around if that becomes a problem over time.
