### ISSUE TITLE
Clixsense problem

### ISSUE THREAD

**Issue by car12** [rainforestapp/tester-chrome-extension#465]
For those that have problem with the Clixsense use the following URL:
http://www.clixsense.com/en/ClixGrid-Play_the_Game That will access the Grid. From there link you can log in and visit all pages except the View Ads. To view and click ads use the URL http://www.clixsense.com/en/view_ads
I already click all available ads.  For the ClixAddon is necessary to uninstall and install again from the URL http://www.clixsense.com/en/ClixAddon and will work. The only link still hacked is the View ads from the Clixaddon. 
Nothing was lost in my account.

**Comment by smt75** [comment]
Thanks for posting the clixgrid link.

That link redirects to google.co.in page

**Comment by car12** [comment]
Yes i just verify and that happen after i send the link here. That shows that somebody is monitoring the posts here.

**Comment by car12** [comment]
From the Clixaddon all links was working but now all goes to google. But the account balance and other info is working

**Comment by smt75** [comment]
Thanks for update. may be we have to wait for sometime more for login 

Happy to know your account balance is safe and working well

**Comment by car12** [comment]
Try this one. Right click over the link and choose to open in incognito window. See if work

**Comment by rnfrst** [comment]
Clearing browsing data works.

**Comment by smt75** [comment]
cleared browsing data. cleared flashdns by typing in cmd command and restarted the PC.

The Url redirects to google.co.in page

**Comment by uangonline** [comment]
I get unsecured connection warning when tried to open clixsense.com. Be carefull!!! The problem still not solve entirelly. Eventhough you can open the site it still not secured.

**Comment by JPierreS** [comment]
ClixSense is working fine, it is not necessary to access other pages.  It may take longer for some people depending on how long your ISP can update the DNS.

A quick fix as explained in this topic:
https://github.com/rainforestapp/tester-chrome-extension/issues/463#issuecomment-244658824

With this you will be able to fully access the site as normal.
So for those who still have issues with redirects can apply this quick fix, uses the google DNS servers instead of your ISP's own.

**Comment by euparkeria** [comment]
You guys know that Clixsense takes 30% of your rainforest payments right? Why use them?

**Comment by JPierreS** [comment]
Because #1) they have a top notch support that answers you, unlike CrowdFlower  #2) they give back a large percentage in the form of bonuses.  With my bonuses + RCB commission that 30% becomes a mere 5-6%, worth it.  With CF Elite you will read stories of people getting delays in payment or account marked as paid but no money received and other issues.   Try to get some answers from CF........
This is where I will gladly donate a % of my income to trusted site owners who care and provide proper support.

**Comment by euparkeria** [comment]
So much for their "top notch support".

**Comment by laga407** [comment]
CF really have bad support, last month i have Withdraw and marked as paid but no money received,
still no answer from CF..
