### ISSUE TITLE
New Type of Error

### ISSUE THREAD

**Issue by Deepak0988** [rainforestapp/tester-chrome-extension#480]
Today while my extension was kept on for fetching work , There was an error showing TOO MANY REQUESTS, It was just like the well known errors like, "Something Bad Happned" "Another Worker Accepted" Etc. Can someone please explain

**Comment by JPierreS** [comment]
The default polling rate in the extension is set to 25, it should be set to 28 to be in line with the actual internal rate limit :-)

If you are receiving an oops link, no vm, refresh at 28 second interval and not 25. :)  I have not seen the error since.

:)

And no, you will not receive less jobs doing so, you will avoid wasting a refresh cycle

**Comment by GreekGuy** [comment]
Maybe it is a new error in order to protect the server from many requests. I believe they add a limit of requests on the server to reduce the response time, so we will not see many times application errors and something bad happened.

**Comment by erdeminofff** [comment]
It looks they increased +2 second to refresh limit with this error message.  If you refresh less than 27 second, its giving this error.

**Comment by JPierreS** [comment]
They actually FIXED it because the original rate was not in line with what was set internally.  Part of 2 of the fix should be done at the extension level and increasing polling from 25 to 28 sec to avoid wasted requests every few.

I see those changes as beneficial - since we all have the same limits it does not impact the amount of jobs received, might even help in some situations - They could also reduce wasted API polling by disabling polling once a link is passed to your browser, as we cannot get more than 1 link and more than 1 job at one time, so as to avoid unnecessary polling during this time, that would help too :-)

**Comment by pscohn** [comment]
This change is a result of moving some of the rate limit code internally - eventually things will be more in sync, but as long as you give plenty of time between refreshes you'll be fine (this is also more helpful if waiting for a vm to become available).

**Comment by Deepak0988** [comment]
Without even refreshing Iam getting this error very frequently
