### ISSUE TITLE
"Too many requests" when I get a HIT, why ?

### ISSUE THREAD

**Issue by Taruga** [rainforestapp/tester-chrome-extension#485]
Why I get "Too many requests" when I get a hit  ?

**Comment by helloworld111gh** [comment]
Wait 3 minutes and try again

**Comment by Electroglitch** [comment]
@helloworld111gh I might be wrong but i think the thing he's trying to ask is why extension sometimes serves link with that message.

**Comment by Taruga** [comment]
@Electroglitch That´s exactly my problem

**Comment by uqbiii** [comment]
But still there are lots of other extensions polling at that time, that's why you and all of us get this message when there is load on the servers. Their next destination must be 300 seconds, it will give jobs to everyone and as they have no way to improve or get rid of these messages, they will change the time limit in the end.😄

**Comment by marius11** [comment]
In that case you should receive the "Another worked accepted..." message.

A job that is successfully delivered by the extension (ie. you can submit it) apparently counts as a refresh, and if you receive another job shortly after you've submitted the first one, that also seems to count as a refresh and the extension will tell you that there are too many requests, so you get this message.

I may be wrong assuming that (1), but I always receive "Too many requests." shortly after completing a job.

(1) The error message is ambiguous and there is another error message that you receive after refreshing a job that is in **progress**: You have requested this job too often. Please return the work.
