### ISSUE TITLE
There is "WOR" always on my extension (no matters ON or OFF)

### ISSUE THREAD

**Issue by rolerpro** [rainforestapp/tester-chrome-extension#508]
Hello, i have whole time green "WOR" on my extension, when i turn off or turn on it's always here. I think that means like i have work (task) but there is no work and that word is always on my extension. Here is picture, my extension is OFF but there is word "WOR"...

![logo](https://cloud.githubusercontent.com/assets/19352000/18412493/4262ca46-7790-11e6-946b-8d02e172b1c5.jpg)

**Comment by jacobcortes** [comment]
https://github.com/rainforestapp/tester-chrome-extension/issues/507

**Comment by guddu007** [comment]
same here always use plugin and seen this "WOR" on my extension, when i turn off or turn on. please fix this .

**Comment by sweeneyapps** [comment]
yeah, it happened when the server didn't let extension know that you re not working.   

my recommendation for this fix is ...   for all of RF's job page and error page, use the implementation of window.onunload to update the extension and the server.    It'll be nice to do that because it's possible tester gave up and closed the "another worker got this job" page, "error" page, or the job page.

**Comment by CharlieSpock** [comment]
Hi, how we can use "window.onunload" and update the extension?

**Comment by rolerpro** [comment]
I deleted extension then again install and it fixed, but i don't know for how long...

**Comment by sweeneyapps** [comment]
@CharlieSpock it's only a suggestion to RF development team.    

@rolerpro You don't have to delete the extension,  you just disable and enable it.

**Comment by CharlieSpock** [comment]
Thanks mate.

**Comment by guddu007** [comment]
I delete the extension and reinstall it but this problem still there. i attach the screen short with activated and non activated plugin in both cases WOR shown .
![w2](https://cloud.githubusercontent.com/assets/22121311/18415394/1ed9b034-780e-11e6-8dce-b898cd45b18b.PNG)
![w1](https://cloud.githubusercontent.com/assets/22121311/18415395/1ee0d1ac-780e-11e6-9977-7ce646ccffd5.PNG)

**Comment by marius11** [comment]
@guddu007 You most likely use an outdated version of Chrome. The lastest version has improved UI which will fix the truncated text on all extensions.

**Comment by guddu007** [comment]
thank you @marius11 i am update my chrome browser but this time it shows "work" in the place or "wor" and it display continuously in activated and deactivated mode but this happen when i see that "another worker accept work before you" after that i close the page and "work" still shown in extension and i found one solution and the solution is i restart my browser when this error occurs and all back to normal.

**Comment by shosti** [comment]
The "WORK" badge indicates that you still have a job that is in progress or processing. It should go away once your last job has finished processing; if it doesn't go away for a while, it's either a bug or an indication that your last job is taking a long time to process (possibly because it was abandoned instead of finished). If it does get stuck on "WORK" for a very long time, restarting your browser will make it go away (I'll work on a better solution next week). 

If you can give me you contributor ID, I can look into whether it's actually a bug or you just had jobs that took a long time to process.

**Comment by shosti** [comment]
Reading through some more issues, I think there is a bug where it gets stuck if you encounter an error in the terminal (such as "No more work"). Should be fixed tomorrow.

**Comment by zfonck123** [comment]
that is a new error, again other hit for tester -_-.. each time to bad to sooo bad ...

**Comment by zfonck123** [comment]
WORK BUTTON STUCK, dont get a job, and the app offline or online, say work....

![1 worl stuck](https://cloud.githubusercontent.com/assets/19192312/18420005/48d3834c-7836-11e6-9c91-3f5c7cd73998.jpg)

**Comment by shosti** [comment]
@zfonck123 I'm aware of the issue and it will be fixed in the next few days. As stated earlier, as a workaround restarting your browser will clear the work notification.
