### ISSUE TITLE
Server is so slow

### ISSUE THREAD

**Issue by Foreverrr** [rainforestapp/tester-chrome-extension#54]
@ukd1 @pscohn 

Guys you should really do something with the server, right now there are 1000 testers online and the servers are running really slow, we lose hits cause the terminal isn't loading and we need to refresh the page, once we refresh the page 3 or 4 times we receive "You have requested this job too often. Please return the hit" message, at least allow us to refresh the page more times before receiving this error.

Also, screenshot function don't work well cause the server is slow, sometimes we wait 2-3 minutes from a step to another because the screenshot function works slow, also, sometimes the screenshot function stops to work and we need to refresh the page in order to be able to complete the hit, so we do the work 2 times.

I believe that this should be your top priority...

For real, why you use Amazon Web Services? There are better options...

It's really frustrating to work like this...

**Comment by begsoon** [comment]
Reason why are servers slow : 

[url=http://postimage.org/][img]http://s30.postimg.org/3lzqk7no1/Capture.png[/img][/url]

**Comment by Foreverrr** [comment]
@begsoon 

That was on February 4, when the servers were down, but right now everything seems to be normal according to their Status, expect GitHub login which doesn't affect us Testers...

**Comment by JPierreS** [comment]
Crazy idea :)
How about a method that would enable instant screenshots and allow us to advance to the next step without any delay, allowing us to complete a HIT in a timely manner.........

How ?  What about storing the screenshots locally (secured of course), allow to continue on the hit, and at the end when submitting the hit, the screen caps would be sent in bulk.  If the server is down it would wait and keep trying until it can reach through -  Perhaps step questions could be "pre-loaded" as well, this could help prevent unnecessary restarting and loss of hits in progress.  So instead of sending screen caps individually each time, they would be secured and stored locally - and send as one batch instead.

Of course that would probably require significant code change :)

So in the case where hosting is down or any other issues, the hit is completed and ready to send.  So with this in mind, and the pre-loaded step questions in mind, this would significantly drop lost hits IMO, of course in theory.

**Comment by AggroTechCyber** [comment]
Yes, everything is normal when they use slower network and database, it works as it is supposed to, but doesn't support a lot of users. And there is nothing wrong with AWS, almost half of the internet uses it.

**Comment by ando100** [comment]
Let`s put something positive here as well, shall we Ladies and Gentlemen? Everything seems to be back to normal, went through with few tasks- all were working like a charm. Props to everyone involved to solve this.

**Comment by Foreverrr** [comment]
@ando100

Everything is working fine cause there are only 600 testers online :)

**Comment by akshithaaravi** [comment]
@Foreverrr How to find out how many users online?

**Comment by Foreverrr** [comment]
@akshithaaravi 

https://www.rainforestqa.com/ There's a bar under the header that is showing live stats...

**Comment by akshithaaravi** [comment]
@Foreverrr Thank you :)

**Comment by ukd1** [comment]
hey all - we don't actually use AWS at the moment, we use Heroku (which is on AWS) and Hetzner in Germany for the VMs.

I hear you re-screenshots; the short version is it's badly designed - currently the request to screenshot goes:

1. from your browser - wherever you live
2. to a server (called "turker") - on the east coast US
3. to another server (called "vmanager") - on the east coast US
4. to a server running next to the vm (called "vcontrol") - in Germany
5. .....and back

So, this is obviously dumb. We're looking to cut out step 3, possibly step 2 eventually. This should make screenshots fast! (cc @jbarber @gallois)


So: a question to you all - why do you refresh the page? What's "wrong" with the VM you get? Do you get one?

**Comment by helloworld111gh** [comment]
Sometimes the terminal goes into a loop of screenshot errors that cannot be recovered from and then you need to get a new terminal.
By logging the errors it seems that the server forgets the terminal exists. Initially it gives "couldn't take screenshot of machine" then it changes to "terminal does not exist or cannot take screenshots at this state" and then will stick at that error eternally.

**Comment by ukd1** [comment]
@helloworld111gh interesting. One thing we're thinking of doing which might "solve" this is to change what happens when you reload; the proposal is you'll _not_ get a new virtual machine - you'll get the same one. We'll add a new button that lets you request a new one, and log a reason + message against it - we'll give you a new one and store the old one for us to investigate. This should mean we'll see this issues sooner and be able to fix :)

**Comment by ukd1** [comment]
(accentual close)

**Comment by jbarber** [comment]
@Foreverrr, @pscohn I believe I'm correct is saying you can resubmit the step to get the screenshot to be taken again?

**Comment by jbarber** [comment]
@Foreverrr screenshots taking 2-3 minutes is very strange. Can you let us know when this happens with the job ID?

**Comment by Foreverrr** [comment]
@jbarber 

As @helloworld111gh detailed explained above, sometimes the Screenshot function stop working, let's say I have a 15 steps test, at a step, the Screenshot function stops, so I can press Yes, No, Step not clear or Other and I instantly get message that the Screenshot couldn't be submitted, even if you try for 10 minutes it will be still the same, so you need to refresh the hit and start from the beginning in order to complete it, so by refreshing the hit you start again from Step 1, so all work you did was lost cause the Screenshot function stopped to work...

Also, yes, 2-3 minutes, when the server is under heavy load, like from 17 to 22 your time (9 AM to 14 PM SF Time), then there are over 1000 online Testers and it's very hard to complete a hit at that time, Screenshot function stops working or it takes 2-3 minutes from a step to another, server errors, application errors and so on...

**Comment by helloworld111gh** [comment]
HIT with broken term.:
https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cxb0f056-8022-43b6-b7be-ab9970b0a18b&browser=any&hitId=4151004&sig=f2b5c23110f7e3e30490c3b25cab449d498751ae74a7fe08f80046de55806b74&turkSubmitTo=%2Fthanks&workerId=12219174
Terminal 9002530
