### ISSUE TITLE
You have reached the maximum number of unsubmitted assignments.

### ISSUE THREAD

**Issue by nummuss** [rainforestapp/tester-chrome-extension#552]
You have reached the maximum number of unsubmitted assignments. So we are fair to other workers, we stop you doing too much for us at once. You can complete the other assignment(s) and refresh this page, or simply return this hit.

Well, actually I did not submit any assignment. So I have no idea what it means "to be fait to other workers".

**Comment by nummuss** [comment]
And also I did not understand what it means "we stop you doing too much for us at once" when I have not done any job before I got this message. :(

**Comment by jackqc** [comment]
Got the same message. It probably means that the system thinks you were doing several jobs at a time. Obviously it's not counting in reloads due to "application error" or "something bad happend" or "no terminal available" ... I just closed the window, hoping that it countsas returning the hit and that I'll get another assignment.

**Comment by nummuss** [comment]
"I certainly wasn't trying to complete more than one assignment at a time."
Same about me.

**Comment by playpin** [comment]
It sometimes takes time to record the state of your job(submitted) 
Clear your history , cache n cookies
that will solve the problem
CCleaner is best for this problem
Try to avoid revisiting old hits

**Comment by jackqc** [comment]
CCleaner is for Windows. I'm on Linux. Sure I can set my browser to clear cache, cookies n history every time I exit the browser, and restart it each time I completed a job. That's pretty annoying though, having to relog and everything. Also wasn't necessary for me ever before, so maybe it needs to be looked into if there's something that can be done without such drastic measures on my side.

**Comment by playpin** [comment]
Not every time  
I do it only once when i get that problem

**Comment by jackqc** [comment]
Okay, it happend again. Got "application error" a couple of times and after a few reloads (note: I did wait some time after each reload) I got that message again. Cleared all the cookies, cache and stuff as you suggested, let's see if this helps.

**Comment by uqbiii** [comment]
This happened to me almost 7 times today and then i turned off my extension. @playpin your information is valid but only for that time when we complete a HIT. 
Why are we getting this error after refreshing a HIT which is not even started and shows error, and that refresh was not manual, extension it self closing the error links and starts to load new HIT url. Clearing Cache/Cookies doesn't have to do anything with this error and i am saying this because i use incognito mode to complete HITs, Have you ever heard that Incognito mode saves cookies & cache? If Yes, i am extremely sorry for your knowledge 😞 .

**Comment by playpin** [comment]
it looks like Automatic closing of multiple tabs is implemented
Its possible that its closing the old tab and opening new one as i also got " maximum error "
 they are stopping us from refreshing many times
some admin pls comment here

**Comment by begsoon** [comment]
So,they forget about error messages ''Something bad happend'',''Application offline'' or ''Connection Error'' where we need to refresh to get a job. because job is alive inside of this errors.

**Comment by uqbiii** [comment]
If they want to stop us from refreshing, there nothing wrong with it, but they should first resolve all these error messages, so we don't have to refresh, except Another worker... and No vm message, every other line/statement is an error. They should resolve those first.

**Comment by nagabhyru** [comment]
@uqbiii what you said is correct. There is a problem with extension. 

I think servers and extension are not paired properly. Extension is unable to distinguish between different type of errors.

**Comment by JPierreS** [comment]
There is a flaw in how the new extension works, it will pass a new link to an existing tab discarding old one.  There are few conditions where this can happen.  You might have received a something bad happened link or app error which was a live hit, but after an interval the extension might be sending you a NEW job link and discard the tab, so the system still sees your active job which you did not access yet.

A tip to avoid this - whenever you get the following links from your extension
* Something bad happened
* Application error
* Any weird or unusual errors

Turn off your extension right away - to avoid it discarding the tab and passing you a new link.
Wait about a minute or more and refresh the tab ( in some instances it will be a live hit )

Code should be added to check the results of the links passed, so that when APPLICATION ERROR, something bad happened, or other fatal errors occur to signal the extension to stop polling ! This will avoid the unsubmitted errors and request too often.
