### ISSUE TITLE
i think i got the same job few times

### ISSUE THREAD

**Issue by djux90** [rainforestapp/tester-chrome-extension#563]
Is it posible to got same jobs more times in a row? I finished one and got second, and i got some error on first step and reported. I again got same job. I think it is same id. Don't know it is bug or something else
![ssss](https://cloud.githubusercontent.com/assets/20422665/18500732/80a00dd4-7a4a-11e6-99f7-46ed7091b76f.JPG)

**Comment by playpin** [comment]
same here

**Comment by uqbiii** [comment]
I figured this issue a few days ago, but don't know either it suits to this statement every time or not, this happens when you open a redirection link of a HIT which was completed, and if you copy the link again and paste, it works. To me, its just copy/paste problem.

**Comment by MarinaCec** [comment]
normal

**Comment by JrRandy** [comment]
If the job is still not processed in the system, when a new link loads it sees it as "refreshing" and you re-start the job.  As you got "Invalid state", that means it finished processing before you loaded the link inside the terminal.  You can actually repeat the job if the processing is very slow, and end up doing the work twice and only getting paid once.

**Comment by JPierreS** [comment]
The reason this is happening is due to a change with the "Thank you page" (endpage) - Before it used to redirect to an mturk submit endpage, if you refreshed that page you would refresh a thank you page.
Now the thank you page does not redirect URL, so if you refresh the same page you are restarting the HIT, and the job link can only be used once.  Once the thank you page appears I just close the tab.

the invalid state means the job was received and being processed or processed and that the job link inside the terminal has expired and cannot be re-used, and even if you re-attempt the job before the link expires, you will only be paid once ;)

**Comment by sweeneyapps** [comment]
@JPierreS  and they need to update their error messages because they are encouraging tester to refresh the page..   lol

**Comment by JPierreS** [comment]
@sweeneyapps  Right ! Indeed ;))

It seems the auto refreshing (new link on same tab) might not be optimal - there instances when a link might be a live hit that quickly turns to one of the myriad of red errors - if the extension passes a new link, user will get the "too many unsubstituted" error.   What I do to avoid this is whenever a link is passed to a tab I shut down the extension, once I finish my hit and reach the thank you page, I close tab and turn back extension.  Of course I only do this whenever receiving anything that is not a working, live hit as the extension stops polling and passing new links.

Perhaps the old method of keeping a tab in focus without passing new links is better for such "special" conditions.
