### ISSUE TITLE
New button in another worker... tab

### ISSUE THREAD

**Issue by CharlieSpock** [rainforestapp/tester-chrome-extension#592]
![2a2](https://cloud.githubusercontent.com/assets/20996862/18681036/39b9e3d8-7f34-11e6-99a6-8db1b5932170.png)
Today i see "RESTART JOB" button when "another worker..." message appear. I use 2 times and i get a "too many request" message. Anyone can use with succes to get a job normaly?

**Comment by sweeneyapps** [comment]
it's because someone asked RF to add "Restart Job" button after Red Error Message.  It's useful when Red Message Error happened while you are working on a job.

**Comment by JPierreS** [comment]
Much like the restart job in your terminal, only this is for external errors, when working on a HIT if you are redirected to an error for example "something bad happened"  - to avoid consuming one of your 4 refresh cycles :)

there is only one thing, it's pointless to have restart job on "another worker" and "no vm" errors as those are not live hits yet - if someone would click on the restart job for "another worker" or no VM errors, it would show a REPORT modal where you would report the another worker error lol that would not be too good (you will get tons of reports of another worker errors lol).

The RESTART JOB should be excluded from showing up for "Another Worker" and no vm available errors.

**Comment by MarinaCec** [comment]
normal...

**Comment by uqbiii** [comment]
@JPierreS I think everyone should understand a line above the Report Text field.
`Please tell us what went wrong with your terminal or job` and if they announce some strict policy on reporting Another... or No VM message, they won't receive much reports.

**Comment by JPierreS** [comment]
Reporting "another worker" has no use in this case it is not a live job, and "another worker" is not a defect, it is expected behaviour - hits are not reserved to a worker yet so the first available person gets it, and if there are no more assignable jobs, you will get this error, which is normal.  This might all be a non issue soon anyway.

**Comment by sweeneyapps** [comment]
love the "No VM", of course because 2k testers are working right now.  :)

**Comment by jackqc** [comment]
The question is ... should we use this button on "no virtual machine available" or just reload?

**Comment by uangonline** [comment]
Funny, i asked to put the button in something bad happened and application error page, not in another worker page.

**Comment by JPierreS** [comment]
@uangonline  The button is there on the something bad error, I had a live hit and it directed to something bad, I used the restart button and it worked fine - I guess by default it is there for every error.  In regards to Heroku's "APPLICATION ERROR" page, I think that would be more difficult ;-)))

In regards to NO VM and ANOTHER WORKER it's pointless to use the restart JOB because no job was actually started  - so you would manually refresh those pages until it converts to a hit, as you are not using up any of your 4 refresh limit.  The refresh limit applies only to live hits.  Besides, once URL refreshing will be disabled, you will need to use restart job :))

**Comment by pscohn** [comment]
The button should be gone from errors unless you've actually received the job successfully.
