### ISSUE TITLE
Red https in rf pages

### ISSUE THREAD

**Issue by RafaelBelmontes** [rainforestapp/tester-chrome-extension#598]
After extention actualization my browser take all Rainforest webpages as non secure pages

![image](https://cloud.githubusercontent.com/assets/22337927/18698647/e2f42b56-7f99-11e6-9049-5a1db4cd3753.png)

**Comment by nerdatwork** [comment]
Check your computer's date. The SSL is working perfectly on RF site.

**Comment by RafaelBelmontes** [comment]
The date and time are correct.
Updated browser, I do not know what else to do.

**Comment by HW71** [comment]
@RafaelBelmontes 
Assuming your problem has been solved because you closed this:
For other users having the same problem (and using the "search" functionality here at GitHub ;-)  ) it would be definitely helpful to know, how you resolved this. Did you change something, or has it been fixed "by magic"?
