### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by LifeIsCod** [rainforestapp/tester-chrome-extension#61]
What to do about this Application Error issue
![screencapture-tester-rainforestqa-com-tester-assignment-crowd_flower-any-1455125391847](https://cloud.githubusercontent.com/assets/7995790/12955670/1e8e4430-d04a-11e5-97d3-b329ea32b577.png)

**Comment by marius11** [comment]
You could refresh or close the tab, but there is already a thread opened about this issue: There is already a thread opened addressing this issue: https://github.com/rainforestapp/tester-chrome-extension/issues/53

**Comment by nishak14** [comment]
Getting screenshot error on the last step! :(

Link of the hit: https://tester.rainforestqa.com/tester/assignment/crowd_flower/any?assignmentId=cx709049-2745-4ee7-a784-ff9e5ea4030f&browser=any&hitId=4531434&sig=e4bf50859921f58845fb092b79415b912207f0fbca519e12befe31c921cfa2b6&turkSubmitTo=%2Fthanks&workerId=34155123

Do you need a screenshot as well? Oh, hold on. It just miraculously got accepted. I tried clicking "OK" to the screenshot error at least 6 times, then spent enough time to create an account here, get it verified, post my problem here, and suddenly it gets accepted!!

**Comment by nishak14** [comment]
Wait. I had an Application error here. Not hit confirmation. Finally, got it on refreshing that Application error.

Why so many problems?

**Comment by RainforestMaster** [comment]
You cant do anything becouse hitler in world war II have a better server than rainforest... For whole day "app error, app down for maintanance, screenshot failed, etc" This rainforest start to be so so its more worth to look in the sky than losing hours and hours doing one hit for 30c becouse of buggy rainforest. my server on pc will work better than rainforest's one...

**Comment by begsoon** [comment]
This is so frustrating ..

**Comment by luisdanielvc** [comment]
I have done like 4-5 test and they doesn't appear in the portal history tab :(

**Comment by Genesis2015** [comment]
I have missing tests in the portal history too :(

**Comment by marius11** [comment]
@luisdanielvc @Genesis2015 They will appear eventually. Sometimes it takes a few seconds, sometimes 15-20 minutes, but they do appear.

**Comment by JPierreS** [comment]
@marius11 
There is nothing CrowdFlower can do for you if you do not see your job in your
rainforest portal history or if the payment is shown pending.  You would only
contact Crowd Flower if the payment was shown in your history as completed (sent by Rainforest)
but NOT received through your channel. Otherwise if the job does not show in your RF portal at all, then it is Rainforest support. :) as per the paragraph in your history at the top of the page.

**Comment by marius11** [comment]
@JPierreS If a bonus is missing, we're told to contact CrowdFlower's support. If a bonus appears in Rainforest's history, but it takes more than 48 hours to sent it to the tester, we're told to contact Rainforest's support.

**Comment by Genesis2015** [comment]
One of the missing tests now appear in the portal history :+1:

**Comment by JPierreS** [comment]
@marius11 read the message in the portal carefully.   If *ALL* payments are marked as paid and none are pending, this means RF has SENT you all the payments, in this case you would contact CrowdFlower, if you did not receive the payment to your CF channel. The text to contact CF support is providing all was paid.   If you do not see the bonus payment in your job history (it did not show up) there is nothing CrowdFlower can do, since it was not SENT by RF yet, in that case you would contact RF support for a missing job payment.  Once the job payment was sent through, it is then a CF issue.

**Comment by hunt40** [comment]
this is not about this error but i have to tell this,i got a hit 15-20min ago , everything loaded except terminal screen stay blank and not loaded then i was thinking why and i know the answer,because of too many user on servers,i waited couple of minutes and refreshed becasuse terminal stuck on and not loadedand its there too many testers error,then i wait 3-4 min refresh the page again same too many user,then wait couple of minutes and refreshed again somebody completed this hit,yes because of your server cant handle amount of testers i lost a hit.

**Comment by masterpeing** [comment]
same error getting around 5 in this day... :( really sad

**Comment by hunt40** [comment]
this is what happens now server error and what you have to but refresh and bam its like my fault

You have requested this job too often. Please return the work.

hard to catch hits nd its gone too because server error,and some people other forums claim they got 5 hits back to back.

so fair great
