### ISSUE TITLE
The problem persists

### ISSUE THREAD

**Issue by NICOSYSTEM3** [rainforestapp/tester-chrome-extension#620]
![image](https://cloud.githubusercontent.com/assets/22378777/18790174/c2bf4e90-817b-11e6-8e65-0a78d36ea7ef.png)

There solution to this conflict have since yesterday morning? :(

**Comment by carlosds7** [comment]
Same problem for me.

**Comment by zfonck123** [comment]
same

**Comment by teckda** [comment]
I have the same problem, not finished loading the VM, my internet is fine because I can download files at high speed and watch HD videos. Still it has not been solved.

**Comment by carlosds7** [comment]
@teckda Where are you from?   It is only with some websites

**Comment by HW71** [comment]
Hi all,

just to make sure: this is about the "terminal not loading" problem, right? If so: we already have an issue for that (see #612) and in order to avoid spreading the discussion (including hints for possible solutions) across different "threads" I'd suggest to close this issue here and continue discussion and posting updates over there at #612.

Just a suggestion, but by the end of the day this will help all of us... :-)
