### ISSUE TITLE
This email already exist ! what's the point ?

### ISSUE THREAD

**Issue by bilelmz** [rainforestapp/tester-chrome-extension#623]
The famous error, when restart a job for some reason, and this job containing a sign up step, then, the error show: this email already exist or something similar.
The question is: what's the point?
The easy answer: report it, but it doesn't make sense.
It's supposed to delete data that has been entered before.
In other words, If you were in the middle of a job containing a sign up step, and you need to restart it, the job is gone! You should not restart it! never!
Again, what's the point?

**Comment by RnkSts** [comment]
If you made a mistake in a registration job and need to restart, sure you can't complete it. The thing you can do it's restart and them when you get the 'Email already used' report it as **NO**, and explain the situation. 

Kristen mention this in the last AMA. Is best to be very very careful in the jobs with registration steps. Also this would be a bit annoying when you have to restart because a VM fail.

**Comment by bilelmz** [comment]
@RnkSts I didn't restart the job for my mistake, but for an error from the rainforestqa website.
I think you don't understand me.
What i mean: there is no meaning to report such thing, it's supposed to delete data that has been entered before.

**Comment by RnkSts** [comment]
@bilelmz I sure understand you, I lost various jobs for this, and end restarting and reporting it in the 'Already taken' step, I mention in #512 , sure it's useless, costumers don't need to know why I restart, but Rainforest may need to know that.

**Comment by bilelmz** [comment]
@RnkSts I hope they change that situation.

**Comment by IceCreamCake** [comment]
@RnkSts can i ask if it happen, report via NO answer and explain the situation is accepted? Usually, i always have to abadon that job by restart 4 times (x4 F5).

**Comment by RnkSts** [comment]
@IceCreamCake according to support, it's accepted and you must provide the details (why you restart the job, if it was a VM error, etc). I think it's no necessary to reload four times, better if you don't want to  or can't continue simply close the tab.

**Comment by IceCreamCake** [comment]
@RnkSts thanks my fr, i really precious your help. That's so much better than what i done.

**Comment by JPierreS** [comment]
Keep in mind when registering on the sites you are testing, you cannot reset this information - remember you are testing an actual site, so the information you are submitting gets stored on the database of that specific site - you are restarting a HIT, but the info you are registering with is already stored on the site's database.  It is unfortunate that you have to restart a HIT due to errors and forced to report this.  To remedy this would be to reset the step variables to give you a new entry (for example when a step variable for e-mail is used, a new one is provided, etc.)   As it is currently, when you restart a JOB, all the dynamic strings in the tests will remain the same.   Hopefully this can be a feature in the future, and it would avoid having to report such jobs  - this would not impact on the quality as the use of dynamic strings returns different results for every tester so it is expected.

**Comment by sweeneyapps** [comment]
@JPierreS I'm thinking.. maybe RF could let test authors define their test.  Such like setting up test's type to run once so nobody can restart the test and knowing test did fail to run through.

**Comment by JPierreS** [comment]
I don't think that might be a good idea, the whole point is for testers to find failures in the application and report it, that's what they signed up for - These type of failures where we are required to restart are not the fault of the customer, so that would only delay results.  For example if a particular test requires registration - and a tester encounters a failure forcing restart, this would prevent customer from getting results, there is nothing much the customer can do about this, whereas allowing the dynamic string to generate a new outcome would allow a tester to enter NEW info and proceed with the test and not have to report to the customer that the info is already used when it is not the customer's fault in the first place.  If I were a customer t hat pays $10k+ a month I would not be too happy if I had test failures due to issues that I cannot control such as non application failures.
When step variables are used, each tester in the group has a different value, so for instance random e-mail dynamic string would be different values for all 3 testers.   Let's say for some reason I am forced to restart a test, this string would be different next time, allowing me to use different e-mail and go through.
If I am a tester t hat has to restart a job at step 50 of 80 for example because of a situation that is NOT my fault, I wasted my time - as I would restart the JOB and have to report on step 3 for instance, how is this fair for me as a tester and for a customer expecting results ?

**Comment by sweeneyapps** [comment]
@JPierreS resetting the variables at restart will for sure solve the problem.  Now there's your idea for RF to implement and it's helpful.

**Comment by RnkSts** [comment]
The costumers want to Test their sites, and they don't want to know we fail the test for a VM Error or any other problems outside the site that we are testing. 

@JPierreS resetting the variables will fix this, But what about all the time wasted? In the case of a very long job. This are special cases and needs to be treated in such a way that benefits both the consumer and the worker.

**Comment by JPierreS** [comment]
I understand your point, I have been in this situation many times and it is frustrating to have to restart a JOB - however this has some advantages, if you think about it, let's say you did 50 steps and have to restart over (which is VERY unpleasant) then let's say the registering is at step 2, then you would earn 8c for all your trouble - With resetting of variables you would be able to reach to step 50 again assuming all works right lol - and at least get paid something!   Customer would get results and you would get paid, although wasted double time but better get paid than not!

Also keep in mind there are failures caused by 3rd parties such as hosting or other issues transient in nature, prompting a restarting of a job - unfortunately it is difficult to predict when these will happen.  Another possible solution to this would be saving of machine states every x number of steps, so when restarting instead of starting from 0 you would start from the last saved state - this is a more complex / difficult process to implement and might not work well in some very specific cases.  I believe a combination of resetting variables to new outcomes + saving states will greatly help - Hopefully with the push of hits and no more polling and balancing of job distribution, we would see less of those errors forcing us to restart a JOB.

**Comment by RnkSts** [comment]
Start again with some new data than be waiting for a new job with less steps, that's greater than ~8c :v 
I also understand that the job you lost can't be paid too, this will create a new goldmine lol. But the saving states idea will be better and 'time saving'. But sure it's more complicated to implement this. Hope an improvement soon.

**Comment by JPierreS** [comment]
The save VM state would be a time saver for sure, but it would potentially require much resources (the saved states must be saved to and loaded from somewhere - adding more server resources + the time it would take to implement this.  Probably the easiest is string regen. :-)))

Let's just hope that these kind of failures forcing us to restart don't occur too frequently in the future,
fortunately, these seem to occur less often now as they used to (knock on wood) and hopefully even less once work pushing is live and job distribution balancing is in effect, but I understand that these cannot be completely eliminated - so let's hope need arises from restarting that 300 stepper anytime soon lol.

**Comment by sweeneyapps** [comment]
hopefully the Rainforest Forum is open to everyone..  then issues on github will be greatly reduced.   To be honest.  This issues on github is mainly for extension problem only.

**Comment by begsoon** [comment]
@sweeneyapps  No,its not open for everyone.

**Comment by RnkSts** [comment]
Well, I like rainforest with issues or not, this income helps me to much. :)

@sweeneyapps yes we need the forum lol, we can share and better organize ideas +many other things. This site if full of non related extension issues.

**Comment by JPierreS** [comment]
Stay tuned - the forum will be opened to all, soon. 

It appears RF has allowed this area to be used as a forum, from day 1 ;)

**Comment by cookin2** [comment]
A new forum with rules and moderators?  Allowing "x" number of members to join daily/weekly?

**Comment by JPierreS** [comment]
@cookin2 Yes with rules hopefully lol - this would be an official rainforest forum for rainforest stuff only.  Initially the forum was open to the few of us ST  - so it is moderated by actual RF people, so no place for soap operas and dramas there for sure.   It looks "different" than the traditional forums most people are used to - it runs on Discourse, it's a Ruby based forum - I personally prefer the traditional threaded forums like CS / NB etc.  I guess that is a question of personal preference.

**Comment by cookin2** [comment]
@JPierreS   Oh my!  That was an eye opener lol  I googled Discourse - saw examples of it.  This will definitely prove interesting :)  Thank you for the info, I like threaded forums too.
