### ISSUE TITLE
May I send the Retrospective message if my pair of testers not reporting bug when they should do it?

### ISSUE THREAD

**Issue by qpPykT** [rainforestapp/tester-chrome-extension#627]
May I send the Retrospective message if my pair of testers not reporting bug when they should do it? In my case I talk about differences in the quotes. I can do it but I don't know may I or not. It can be powerful tool for cleaning inappropriate testers who systematically violate the rules.
**Ps:** Could you set transparency for lines about 50-60% on the retrospective screenshots sometimes these lines overlapping text.

**Comment by nerdatwork** [comment]
Of course you can. I didnt get the transparency part of your issue. Could you explain a bit more ?

**Comment by uqbiii** [comment]
I got my first email on 24 and i was amazed to see that i logged in successfully and others reported. If my login credentials are correct, why their credentials are not correct?

**Comment by sweeneyapps** [comment]
oh are you talking about the new job feedback feature?

**Comment by qpPykT** [comment]
@sweeneyapps 
Yes, I'm talking about new feedback feature. Rf send email you when you have passed hit but others workers in your pair has failed the hit because of some reason. 
I was thinking about this - there is an opportunity to send a message when you report bug but your pair passed the hit and did not reported bug Rf did not send you email in this case. But never mind.

@uqbiii 
It can be because of lags on the sites.

**Comment by hunt40** [comment]
i did a proper job and i got that message then i send my comment because i did the job correctly,some other workers perhaps have some browser problem or something then.but what is funny they say something this is a learning opportunity, not a rejection,its like we did that intentionally  there is tons of connection errors and other kind of browser errors,script etc. who you can report but not happen to other testers they should think that too and not act according to this information.
