### ISSUE TITLE
Extension requests to often

### ISSUE THREAD

**Issue by 2codefast** [rainforestapp/tester-chrome-extension#635]
In last two hours hits go in to often because extension pulls them too fast, did not measure time but its less than 2 in 75 sec

**Comment by nuevao** [comment]
if, like me, the extension opens the window for a possible job opportunity but it is not, and suddenly charging more than twice automatically very quickly. A unproductive day.

**Comment by mobradovic** [comment]
I saw a lot of those too. I don't refresh, like, ever. When (whatever) error appears, I close the tab, and extension pulls another tab few seconds later, which very often result with "Rate limit exceeded, you may do 2 requests every 75.0 seconds. Don't refresh the page more often than this." Again, I do not refresh.

So, looks like extension issue, counting closing tab/serving another as refresh, and/or pooling to soon.

**Comment by shrestha15207** [comment]
things have been more difficult for testers after extension keeps on opening 'too much request' page. i turned off extension for 3-4 mins, and it still it opened 'too much request' page.

**Comment by JrRandy** [comment]
I believe that this error is NOT you requesting too much, I believe it is the server spitting an error that IT is receiving too many requests but that is just speculation.  Due to the ambiguous nature of this error, it does not clearly state which side is causing the error.  The rate limit exceeded error is very clear, and I do not believe this error to be related to that one.

**Comment by mobradovic** [comment]
Agree. "Too much request" error is to be seen in the console occasionally, without tab being served/opened by extension.

**Comment by nagabhyru** [comment]
Yes I am also facing this issue. Extension pooling too many in less time (75 seconds). All the jobs are ending either with following errors
There are no virtual machines currently available. Please retry in a few minutes.
Too many requests.
rate limit exceed. 

some times it even opening 2 to 3 jobs in less than a minute, resulting rate limit exceed. Today I lost almost all jobs because of this. Unproductive all the day.

**Comment by shosti** [comment]
No longer relevant as we've moved to push mode.
