### ISSUE TITLE
please help Only training jobs

### ISSUE THREAD

**Issue by javicocuba** [rainforestapp/tester-chrome-extension#649]
34 jobs training.
I'm bored, frustrated think my best days have passed with rainforest, simplemete can not devote the entire day to just do jobs training.

**Comment by javicocuba** [comment]
porqueria

**Comment by HW71** [comment]
@javicocuba 
Well, actuallly this repo / issue tracker should only be used for problems related to the chrome-extension (the name of this repo already indicates this).

Now due to lack of other communication channels (some kind of discussion forum is currently evaluated) this tracker has more and more been used as a "general" Rainforest support platform (which was never the intention).

Nevertheless the project member seem to keep "off-topic" discussions going - at least as long as they are related to RF issues.

I can only guess, but this 

> "I'm in the training Sandbox-loop - please help!"-thingy

has been answered quite often in the meanwhile (see #632 or #600 for example) - and it's also listed in the [FAQ](https://github.com/rainforestapp/tester-chrome-extension/wiki/Training-Tasks) (please see especially topic 3 there) so this _might_ be the reason why your issue has been closed without further notice...

HTH & Cheers, Erik
