### ISSUE TITLE
Blocking policy

### ISSUE THREAD

**Issue by braneb** [rainforestapp/tester-chrome-extension#66]
If tester get "you request this job too often" message will he be blocked...because most of the time its because too much workers requesting a job/we reached maximum amount of testers....this rules egzisted always but it seems like its getting serious now...obviously it becames even more stresfull ti be a tester...

**Comment by pscohn** [comment]
@braneb you won't be blocked for this reason. Today we published our blocking policy in the "Help" modal that appears during tests, which you can also see right now at https://tester.rainforestqa.com/guide.

**Comment by ando100** [comment]
@pscohn   Paul, let me do a walkthrough for you to end with beautiful solid Block..
Step1. Tester gets a hit through extension and it shows for example 10 steps, but tester 
can not open or click on it, because screen turns to:
We`re sorry, having too many concurrent users etc.. please try again later.
Step 2. Tester waits few minutes 
(timer is ticking 10/15 minutes)
Step 3 Tester retries.
Same issue- tester can see that test has been assigned, but getting message-
Sorry, we have too many...
Step 4.
Tester is already worried checking timer and all clocks available, then scratching his/her head. Having
glass of cold water perhaps. Waits.
Retry. Again out.
Step 5.
Tester waits a little more- then gives it another, the last try, hands are shaking,
blood pressure- code red- click with mouse and
Bang
You have requested this job too often, please return...

WWW- what went wrong?
referring to:
Headline: Examples of bad behavior that will result in a block:
Answer: Accepting jobs and failing to start them in a timely manner.

Tester accepted the job/ task but failed to start it, not depending
his/ her actions.

Please prove me wrong :)
Thanks.

**Comment by pscohn** [comment]
@ando100 what you described is not what we define as "accepting a job." We could clarify this in the guide, but "accepting jobs and failing to start.." means you have successfully gotten a job with a terminal that works, you are on the first step, and then you decide go watch a YouTube video, or take your lunch break, meanwhile the test sits there, not being done by anyone... we won't block you for something that isn't an obvious violation - i.e., errors in getting jobs is our fault, not yours.

**Comment by ando100** [comment]
@pscohn Paul, thanks, this brought up 2 options and no, I was not meaning
               any YT or lunch.
1st. As I described. No YT or anything- how does your system detect this- 
      Tester gets a job ( task assigned) and tester failes to start it at all, because- 
       first screen is :  " too many concurrent..."  Fail+ fail + fail= tester has 
      requested this job too often. Out.
      And how will it be marked into tester history? +1 job will go into testers history> Total Jobs    AFAIK.  Abandoned or not?
2nd: As you described: Tester gets a task, starts all ok, is on 1st or 3rd or even 17th step as some testers have referred> gets - "Failed to send screenshot" error. Or Application error or any " you name it " error. He/She restarts the task, gets- " too many concurrent..."... Waits, restarts... Same issue. Few more tries- he/ she gets this: You have requested.... please return.. And no more retries, as 4 starts have already been used.
So based- what you told- this is the successfully accepted/ started task in eyes of your system- and tester is knocked out. Not depending on tester at all- but will show up in tester history as- he/she abandoned the task.- though they did not. Correct?
My question is: how is it separated in your system or is it at all- the above cases.
Testers themselves do not get any information as of now and do not see any problems if
occasionally once or twice per month or now per week the situation happens, but is recorded still to their history.
When will they see the problems or do they at all? How do you differentiate- when was for example system outage or when tester quitted by his/her means (YT/lunch).  Example- one guy gets outage, 2 testers- for same test- join in little later > site works and can complete successfully, how do you know- the one- who "abandoned/quitted/ did not show up/ anything" did not do it on his/her will but- during system failure?
Re:  i.e., errors in getting jobs is our fault, not yours--this is the main thing I want to confirm-
that you are perfectly aware- when its not tester`s fault.
Sure, the account does not go into block on 1st try, but these are the small, but important xyz situations I see at the moment.
Thanks.

**Comment by pscohn** [comment]
@ando100 

First scenario - the job may be marked as abandoned in some of these cases, but we don't consider that to be "failing to start." Once you land on the test page, can see the first step, and have a terminal, if you do not make progress on the test and are marked idle than that can count as failure to start. Even if there is still a problem with the terminal, you may refresh or report errors, but if you do nothing at all, that is "failure to start."

Second scenario - more or less the same answer, we only care that you are actively working on the job. Errors are not your fault, but if you stay on a test page for 10 or 15 minutes and do nothing, that is a violation of our rules.

Tests can become "abandoned" for a variety of reasons including errors, but only the ones where you are sitting there on the test page doing nothing will count against you.

**Comment by ando100** [comment]
@pscohn thanks, ok, but I guess- you are forgetting one really important thing-
when "Failed to send screenshot"- appears- tester can NOT do anything, but restart,
if restart fails and again fails- there remains pure desert without any Rainforest :) , what ends with- You have requested...
Tester can NOT REPORT anything.. 
And that test goes to: ....Abandoned, correct?

thanks.
ando

**Comment by ando100** [comment]
I assume you got it >  but re:   if you stay on a test page for 10 or 15 minutes and do nothing>
means the very possible situation- failed to send screenshot...from tester`s end has occured.
I mean testers who do tasks and not YT etc. same time.
I speak from my experience.
thanks.
ando

**Comment by pat87** [comment]
Hi pscohn. Could you please clarify what is meant by "Once you land on the test page, can see the first step"
I have been guilty of falling asleep with Chrome on and woken up to see I got a hit which was timed out. But I never entered the initial url and took a screenshot and never got to the "first step"
While the new idle policy (where the extension turns off automatically) would help, and I too would take more care now that I know it is not something you guys like (didnt realize it was an issue), 
I was wondering if that is considered "accepting a job"

Or do we only accept the job when we enter the initial url and land on the website we are testing. 

Also, I agree with ando100 that there are times, especially with mac osx and safari and the iphone emulator, where the terminal just doesnt respond after a while.. the cursor stops moving and the pages just hang. We have been asked not to report errors when the problem is with the terminal and not the website.
Restarting those hits can lead to all sorts of errors.
