### ISSUE TITLE
Still cannot change Contributor ID?

### ISSUE THREAD

**Issue by Remesa** [rainforestapp/tester-chrome-extension#663]
I work for rainforest since 2014.
My old N**bux account was suspended in 2015 because of inactivity, and now, i came again to make money, and my Contributor ID is different, on Crowdflower i can change the ID from CF, but no on RF.
I can´t work again because of this :( my money never appear in my Neobux account

Recently mail i receive:

> Hello,
It's currently impossible to change payment channels (see the FAQ: https://github.com/rainforestapp/tester-chrome-extension/wiki/Frequently-Asked-Questions#can-i-change-my-crowdflower-id-used-for-payment) or your Rainforest ID. We're sorry for the inconvenience! We'll update testers if this changes in the future. It's important to note that if your Rainforest profile has been blocked, you are prohibited from ever creating a new ID in the future.
If you created a new profile using "Test Applications For Rainforest QA" while this option was still available but didn't complete your account setup, you can do so by clicking the "Claim it" button on your profile and following the instructions sent to your CrowdFlower inbox.
Sincerely,

**Comment by qpPykT** [comment]
@Remesa You have the answer. Why you opened new thread? They can't change your ID number.

**Comment by Remesa** [comment]
Wanted to know if in the future they will change that

**Comment by qpPykT** [comment]
@Remesa If in the future it will be available they will inform all testers.

**Comment by HW71** [comment]
@Remesa 
The problem is, that currently (and maybe "forever" ;-)  ) a Rainforest account is linked 1:1 with a CrowdFlower ContributorID. And for every Crowdflower Payment channel you have exactly one ContributorID. That means: if RF would allow to change your ContributorID this would automatically result in a new, vanilla Rainforest account.

There are some interesting discussions ongoing about that => see for example issue #463. There I also added some information from the latest "Ask Me Anything" September session. 

So in order to not have multiple issues for one and the same thing I'd suggest to close this issue here - and maybe follow the discussion in #463. Unfortunately 463 has been closed (which might be "OK" because it's not related to the Chrome extension anyway), but nevertheless it's an important issue because from the number of questions raised in the AMA sessions one can see that this "Get paid using different ContributorID / Offer different payment options"-thingy impacts a lot of people.
