### ISSUE TITLE
problem with the plugin

### ISSUE THREAD

**Issue by roko777** [rainforestapp/tester-chrome-extension#670]
I can not update the plugin. old removed, and the new is not installed. write error  How to solve this problem?
![1](https://cloud.githubusercontent.com/assets/16417121/19170599/cb576550-8c21-11e6-9889-e43d42379f86.jpg)

**Comment by JrRandy** [comment]
Typically Write Errors are caused by something blocking it.  Not sure if you have an outdated version of chrome or something?  Also notice in your SS that your https is crossed out, meaning your not recognising the security certificate or something.  Not sure if related, but figured worth mentioning.

**Comment by roko777** [comment]
everything is new, the latest version of Chrome.Installing the plugin is interrupted Download interrupted
![1](https://cloud.githubusercontent.com/assets/16417121/19171587/304e7b48-8c26-11e6-81de-6f8dcffb4e18.jpg)

**Comment by roko777** [comment]
solved a problem. The bug was in the host file (driver) .There is necessary to remove the inscription -127.0.0.1 clients2.google.com

**Comment by roko777** [comment]
Why is a new plug-in PC scolds. supposedly dangerous to your computer.
