### ISSUE TITLE
Is my answer is correct

### ISSUE THREAD

**Issue by awnosa** [rainforestapp/tester-chrome-extension#696]
In this step is not shown the email that i will log in and  password not same i used to update old password in previous i reply no Is my answer is correct I received this task more than once and  i want reply correct

![3223](https://cloud.githubusercontent.com/assets/16338438/19234518/04702116-8ea1-11e6-9543-d066e0d0deb7.png)

**Comment by RnkSts** [comment]
I'm not sure if I understand you or if this is what you want to know, but I have completed a similar job few time ago.

I failed that test for two reasons: In the page there was no top menu or Log out button (_This reason was enough for me to fail the test_). And the second reason is that the password mentioned in the instructions (_in my case_), was the same password used for register, that was replaced by a new one in the restart password step before this, so obviously if the 'log out' button was present maybe I will fail the test (_I think it was a mistake by the task author_).

This is another case of vague instructions. Plus, If the log out option was present in the top, The instructions don't provide the email again, you can get it from an earlier step unless the email was already filled in the log in form, another thing that need be treated by the rainforest team and/or give us another update in the wiki about that.

**Comment by nerdatwork** [comment]
@awnosa You did the right thing by replying NO. Always explain why you said NO in the pop up in detail.

**Comment by sweeneyapps** [comment]
@awnosa we can't really help u that much because not enough details to this kind of job assignment.   It could be, the previous instruction asking you to update the password and during that process... you are supposed to click continue after receiving password update message.  To be honest, I see a way to access to the account so I would click continue and look for Logout button.   But if you want to be strict with the instruction, that's ok.. just click No if u can't logout.

**Comment by ellmirr0001** [comment]
I successfully finished this job. You should log out from the page and again log in with same email you used in previous steps and use new pasword which you used for reset. As I can understand you couldn't find email and pasword in this step but if you hoover your mouse over previous step there is a tooltip with a question from previous(that)step and there you can copy email and pasword since they did not provide email in this current step. Hope this helps

**Comment by nerdatwork** [comment]
@ellmirr0001 This is **not** the right way to do this job at all. You should have reported the job at the above shown step. The instruction does **not** ask you to copy email from previous step. This is why you need to follow instructions to the letter.

**Comment by ellmirr0001** [comment]
But the question in this step is to log out from the page and log back in with a new pasword, since in my clipboard is  only copied pasword the only way to find email is to copy it from prev step.

**Comment by sweeneyapps** [comment]
we should let @kristen-allie take care of this question.  👍

**Comment by Electroglitch** [comment]
This is clear NO test author didn't provide you with email to sign in or you were instructed to copy/write  it in previous steps.

**Comment by VeryDisappointedTester** [comment]
As far as i can see there is not enough data to proceed to next step.
We are not allowed to do anything that is not mentioned in instructions.
Since instructions say to log in with password and don't mention email this is 100% NO.
There is no mention to use email provided in previous steps.

**Comment by nerdatwork** [comment]
@awnosa if you are satisfied with the response you got so far please close this thread.

**Comment by awnosa** [comment]
thanks to all for reply me
