### ISSUE TITLE
Too many screenshot problem occur..

### ISSUE THREAD

**Issue by rbasak2011** [rainforestapp/tester-chrome-extension#7]
I just got a hit with 12 step..At the last step there is a problem taking screenshot after i clicked "yes" button..Then i refresh the hit and do it again but same problem occur again at the 12th step..Then i try several times to take screenshots but problem persists..Then i refresh again but this time it shows "sorry we have reached the maximum no. of concurrent user.." >By the new rules i have to refresh again within 5 minutes so i did and the "you have requested this hit too often"..So i did this hit 2 times but i got nothing from it and the most worst part is i my accuracy also reduced because of this...

**Comment by ando100** [comment]
You got my attention with- "my accuracy also reduced because of this" -
how can you tell that?
Well, I`m not from RF, but after reading your message- I can tell you ONLY 
from my experience- wait for the " Screenshot can not..." - it solves in time.
You even don`t have to restart the whole task, I can imagine your frustration,
while getting this message in last step, but, yes, my suggestion woud be, wait a little
and try again.
Again- this is my personal opinion, nothing official.
And if you don`t mind- please guide me to the part- your accuracy went down?
Ando

**Comment by ukd1** [comment]
@rbasak2011 sorry about this; it doesn't actually affect your accuracy on our platform, though it obviously takes up your time unnecessarily. 

Did you happen to keep the job id for this?

@gallois perhaps we should move the screenshotting to go direct to the vcontrol, rather than routed through vmanager?

**Comment by gallois** [comment]
@ukd1 this would avoid an extra step in the process of taking a screenshot, but also having configuration variables spread over more places, which could lead to a more difficult maintenance. We could retry the screenshots inside vmanager as well.

**Comment by ukd1** [comment]
@gallois ya - more config, but less complexity and also won't matter if vmanager is down -- i.e. would be totally out of the picture after the tester got the machine?

**Comment by BV25** [comment]
@ukd1 Hi Russel, lately there have been a lot of screenshot problems - on an average they resolve however it is seen that sometimes it takes more than 15 minutes for it to resolve - now, because of the new idle rule - if you don't proceed to next Step within 15 min (i.e. if you don't click any of the button) then you're automatically disconnected and you see "connection lost" message. This is kind of unfair and should be looked upon - I've lost 4-5 hits past week due to it. I also find "Application Error" messages almost daily multiple times. 
Also - the worker is right about Accuracy. All these Jobs lost go to abandoned count and it lowers the Accuracy as well as it increases the abandoned count. Please do something about it, thanks!

**Comment by pscohn** [comment]
A recent complaint from an mturker:

```
For Step 4 in a HIT I attempted, I kept getting an error message that there was a failure in taking a screen shot. I answered "Yes" 3 times and received the screen shot error message, then answered "other" and still received the screen shot error message. When I tried to reload the HIT, as the Help instructions said to do, I got the message that stated I had too many unsbumitted HITS. The only HIT I had was the one I was having problems with. 
```

**Comment by nuevao** [comment]
Greetings guys, this problem has become very frequent tests performed in less than 3 minutes take up to 10 minutes so slow taking Screenshort. and the typical error message when not slow appears "failed to report Screenshort ..." which generates many times that you can not complete the test. It occurs most often from Monday June 27
![capturafallo](https://cloud.githubusercontent.com/assets/16979522/16503276/51f4ac4c-3ee0-11e6-800c-dc41f06c8620.JPG)
