### ISSUE TITLE
Unable to login in My profile for Rainforest Tester

### ISSUE THREAD

**Issue by manishflyboy** [rainforestapp/tester-chrome-extension#72]
I have claimed my profile and doing tasks also
but from past two days Iam unable to login into my profile.
It is showing Invalid email/password.

When I select the option of forgot password no Mail is sent on my crowdflower id.

Previously I was able to login but from past two days Iam not able to login.
My worker ID is 33361128

Please Help

**Comment by erdeminofff** [comment]
Did you use another rainforest account in past? Why I am asking, because they are connecting all past accounts to one, sometimes combine under first account. If you don't remember your old account email, can see from extension

-Go to chrome://extensions adress in chrome
-Select Developer mode check box from top right
-Find Rainforest Tester Extension and click "background page" link
-Go to Network tab
-Enable your rainforest extension like that  ![ashampoo_snap_2016 02 13_18h10m48s_003_](https://cloud.githubusercontent.com/assets/8877357/13028664/e6ea8b52-d27d-11e5-82f0-0d05ad285afc.png)
-Wait a few seconds until links appear on the white field.
-Hover over any link, a link baloon must be appear. Now, you can see which account email rainforest uses for giving hits.
![ashampoo_snap_2016 02 13_18h05m11s_002_](https://cloud.githubusercontent.com/assets/8877357/13028694/25df3640-d27f-11e5-93a6-894a50457ff3.png)

If it's different from currently uses, try to login with this email or use for password recovery. You must get mail on your crowdflower mailbox.

**Comment by manishflyboy** [comment]
The email address which is shown is same what Iam using for logging in. But still no progress. And when I click forgot password no mail is sent to my crowdflower mailbox. This is my only rainforest account.

**Comment by pscohn** [comment]
@manishflyboy have you sent an email to tester support?

**Comment by manishflyboy** [comment]
In the terminal it was showing email rezahaqu@gmail.com (Unknown). I tried login with this email and my password and I was able to login. after login in to my profile I changed my email and now the issue is resolved.

**Comment by jmheinz** [comment]
hello guys....I have a problem similar to this...Its almost 3 weeks..i can't even reset my password..
