### ISSUE TITLE
Educational quests.

### ISSUE THREAD

**Issue by skotos1981** [rainforestapp/tester-chrome-extension#731]
Greetings!
I go 3 day avalanche training tasks. They have no end is already dreaming. Help, do something. I would like to have normal work ...

**Comment by HW71** [comment]
Hi @skotos1981,

this GitHub Repository is just for discussions related to the Rainforest Chrome extension. For all other topics we have now this great forum here:

http://forum.rainforestqa.com/ 

Hence, I'd suggest you close this issue here and post post your concern in the new forum in order to keep this GitHub repo focused on the Chrome Extension.

Kind regards & Cheers, Erik
