### ISSUE TITLE
Job rejections on training

### ISSUE THREAD

**Issue by StarguardianLUX** [rainforestapp/tester-chrome-extension#737]
wut?? 
![Uploading s.png…]()

**Comment by ladystoneheart** [comment]
wut 
![s](https://cloud.githubusercontent.com/assets/20522240/19618209/4d5d5b32-984c-11e6-9140-2764bc464e27.png)

**Comment by ladystoneheart** [comment]
i don't really saw any wrong about in my work please make me understand

**Comment by ladystoneheart** [comment]
2nd rejections

![1 0](https://cloud.githubusercontent.com/assets/20522240/19618243/3a1d793e-984d-11e6-942b-6996bdb47924.png)

![1 1](https://cloud.githubusercontent.com/assets/20522240/19618245/3ffa6718-984d-11e6-9073-6d2d481414d8.png)

**Comment by helloworld111gh** [comment]
Can you clarify what problem you are having with the extension?

**Comment by marius11** [comment]
@helloworld111gh He doesn't have any problems with the extension, probably doesn't know that Rainforest has a forum for its users to use for issues not related to the extension.

https://forum.rainforestqa.com/

**Comment by uqbiii** [comment]
Rejection is fair because you used 1 password 2 times in password field for registration. And please use forum for such issues.

**Comment by HW71** [comment]
@StarguardianLUX 
As already mentioned: both rejections were fair (also the first one with "US-8" and "USA-8") - but if you still have concerns about them (or want to discuss things) please feel free to post in the official forum already mentioned by @marius11: 

https://forum.rainforestqa.com/

=> Please close this issue here because this repo should only deal with the Chrome Extension.

**Comment by helloworld111gh** [comment]
*GO HERE FOR NON-EXTENSION RELATED SUPPORT*

*VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV*

https://forum.rainforestqa.com/

*^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*
