### ISSUE TITLE
Extension stays "WIP"

### ISSUE THREAD

**Issue by cookin2** [rainforestapp/tester-chrome-extension#741]
It's happened on and off for days (no pun intended).

It just happened right now and of course when I went to take a screen shot it fixed itself.

Under submitted on my portal as the last task I had completed:  2016-10-25 20:14:30 UTC

I didn't notice it until just now - 4:50 my time.  It took a few minutes to write this, so my extension stayed in "WIP" state for at least a half an hour.

**Comment by shosti** [comment]
Could you give me your contributor ID? I'll look into it...

**Comment by cookin2** [comment]
Thank you :)

I've sent my ID via email to you - I trust that's ok.

**Comment by sweeneyapps** [comment]
from my observation.  It did happened to me once..   Extension would stay WIP after being disconnected from the internet before the server is able to send the workFinished message.

**Comment by RnkSts** [comment]
Sometimes when I finish a hit, the extension stays "WIP", but I can receive jobs without problem ( I tested it), so for me i think it's a problem with the icon (?)

**Comment by shosti** [comment]
@cookin2 @RnkSts what version of chrome are you using?

**Comment by RnkSts** [comment]
![screenshot_4](https://cloud.githubusercontent.com/assets/20311303/19749767/bb4284b8-9bb9-11e6-82a1-fee62231b722.png)

**Comment by cookin2** [comment]
@shosti    Version 54.0.2840.71 m

**Comment by marius11** [comment]
This happens to me too. The "WIP" tag stays on anywhere between 10 seconds to up to 2 minutes after the job is submitted.
I'm using the latest Chrome browser, 64-bit version.

**Comment by Zunami007** [comment]
That happens to me too sometimes. When it takes longer than 1-2 minutes I just restart the extension 
Chrome version Version 54.0.2840.71 m (64-bit)

**Comment by HW71** [comment]
Hi all, 

just to make sure we don't chase shadows / mix-up things here:
there _might_ be a real issue - but at least what I remember time frames ranging from "some seconds" to 1-2 minutes are absolutely OK, because this is the time it could take until your results have been processed by the "backend" after you submitted them. So everyone experiencing a "WIP"-timeframe as outlined above shouldn't be worried.

Maybe I'm wrong, but that's what I've learned from another discussion here at GitHub (don't have the issue number at hand, though)...

Nevertheless there might be circumstances causing the WIP to stay "forever" (for example "loss of internet connection" as mentioned by @sweeneyapps). And of course there might be an additional issue...

**Comment by cookin2** [comment]
I haven't had a recurrence of the 30+ minutes episode.  I have had WIP for short periods of time - maybe a minute at the most, so nothing to worry about there.  

Interestingly enough, @RnkSts is right - in the Developer's Tool page, I see status ok and I'm pretty sure that it's looking for work?  I agree, it looks like an icon issue rather than something being wrong with the extension.

I'll defer to @shosti as to whether this issue can be closed or not :)

**Comment by shosti** [comment]
Keeping open for now because we can fallback better in the rare case that it actually gets stuck in WIP.

**Comment by Vittalev** [comment]
Hello @shosti 
My extension got stuck today at WIP mode and it has been in this state for 2hours+ now.
Could you take a look for me?
Thanks

**Comment by helloworld111gh** [comment]
As a proposed fix, maybe send the current worker state back during the heartbeat? So if the extension didn't get the "WORK FINISHED" message, they'll get it during the next heartbeat.

**Comment by Vittalev** [comment]
Hi, I'm just passing by to say I don't know what caused it or what fixed it but I received a hit some minutes ago so I guess it is working as intended again.

Thanks.

**Comment by iOXiNG** [comment]
Hi, I finished a job almost an hour ago and the Extension icon is still in WIP mode. And the job showed in my history page almost an hour after completing it(it showed directly as "paid'').
Apparently my chrome wasn't up to date, when I checked it was Version 56.0.2924.87 (64-bit). 
(Now it's being updated. I have to re-launch chrome to finish updating) 
Was the problem because my chrome was not up to date? 
Note: this is the 2nd time it happens to me. (first time was few days ago).

**Comment by amabrj** [comment]
I don't receive jobs! =/

**Comment by manivelasm** [comment]
no hits for me please give

**Comment by amabrj** [comment]
I don't receive jobs! =/

**Comment by kaisaoussen** [comment]
Hi, i had the same issue yesterday the icone appeared as WIP with the sound i have set for work but there was no work and after this i was disconected it happened twice yesterday to be disconnected when i was active, i use the lastest chrome version, and 64 bits.

**Comment by CarlosBoggiano** [comment]
Greetings and Merry Christmas. I had a problem with the extension and it did not enter the system again, I uninstalled it and reinstalled it, but it did not finish installing, I already rebooted my PC but it did not finish loading again. Hat some way to install it manually.? Unpacking it from another part? I hope you help. Thank you all. Google Chrome Version 49.0.2623..112 in Windows XP SP2
