### ISSUE TITLE
Feature Request: Confirm Notification when there is HIT

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#742]
On the tester forum there was a suggestion about having a confirmation notification when there is a HIT, here's the topic: https://forum.rainforestqa.com/t/suggestion-for-when-there-is-work/2203

> estevao_lage 4d
> I'd like to know if it's possible to have a notification pop-up telling us there is work available, instead of a new tab immediately appearing. We would then click the notification and the hit would open in a new tab.
> 
> Just now i accidentally closed the hit tab because it appeared the moment i was trying to close a different tab, and unfortunately there is no way to reopen it because it doesn't show in my history.

Other ideas proposed in that thread:
- You can decline the HIT if you're not ready or don't respond, which will abort the HIT immediately instead of having to wait 10 minutes for idle timer (to prevent abuse a lockout could be possible)
- If you don't respond after some time (30-90 seconds) or decline the HIT, the extension turns off
- Show the number of steps in the job so that you don't have to do long tests if you don't have time
- Same idea as above, just only have a warning if the test has more than X steps
- While the notification is being displayed the sound notification could constantly beep

I'm just putting this here so that the devs can have some input on this (as I don't think you're on the forum)

**Comment by shosti** [comment]
Definitely seems reasonable--probably should be optional, since some people will want the more efficient workflow. 

The implementation shouldn't be too hard: basically we just show a notification that stays on for 30 seconds and then turns the extension off if it isn't clicked, and opens the tab if it is clicked. The job will time out in 1 minute anyways if it isn't started. 

@rainforestapp/tester-product thoughts? Not sure how to prioritize this...

**Comment by qpPykT** [comment]
30 seconds it is too little maybe at least 60 seconds.

**Comment by rnfrst** [comment]
I think the notification is too much or is not necessary, as @shosti said, some (or even most) people likes the more efficient workflow. I would not want to click one more window or popup just to open the tab. This notification was suggested because the tester accidentally closed the tab and could not find it in the history, where in fact can be located in the network tab of the extension.

**Comment by ikjt** [comment]
This should definitely NOT be a default behavior. Extension works very well currently. Opening a new tab and loading the job right away is great. It's quick and there are very rarely any problems at the moment.  And I like to start working as soon as the tab has opened. I really don't see why it's necessary to add additional notification for accepting the job. 
My only dislike is still with the extension closing the tab, but most testers seems to be fine with that, and it's no longer causing the problems since we now only get preassigned jobs.

I'm just curious, do people really have that much work that they need a feature to decline the jobs. The forum is full of posts about the lack of jobs. If someone is doing something else and doesn't want the jobs at that moment, why not just turn the extension off for that time period? At least that's what I do.

When I turn the extension on, I'm ready to work. I don't see why it's necessary to have another popup notification at that point for accepting the job. Turning the extension on should be enough to let RF know I'm ready for the jobs.  :)

Just my two cents. :)

**Comment by shosti** [comment]
> This should definitely NOT be a default behavior. Extension works very well currently.

We'll definitely keep the current behavior as the default.

> 30 seconds it is too little maybe at least 60 seconds

Since we want to make sure this doesn't lead to jobs getting completed slower, 30 seconds makes sense to me (we timeout in 60 seconds anyways).

**Comment by sweeneyapps** [comment]
other idea here to put some user's options in the context menu (right click on icon).  I did talk about it on the forum and it seems easier for user to quick set their options there.   Useful for this situation and easier to organize settings for job notifications and sound setting there.

example image: 
![image](https://cloud.githubusercontent.com/assets/7229364/19747532/13bbb4e4-9b91-11e6-8a29-5d2be076b293.png)

**Comment by shosti** [comment]
not a bad idea (I didn't actually know about that), but I think that can be a separate issue.

**Comment by sweeneyapps** [comment]
yeah, just dropping in.  :)  I'll open another issue for this.

**Comment by ikjt** [comment]
Thanks for keeping the current behavior as the default, @shosti :)
