### ISSUE TITLE
Unpaid work.

### ISSUE THREAD

**Issue by teckda** [rainforestapp/tester-chrome-extension#745]
Hello,

I have performed several tasks that are not "tests" which have not been paid. In the job history are reflected in "-" as if they were "test".

![11](https://cloud.githubusercontent.com/assets/22463976/19824069/7f156212-9d3a-11e6-9efa-cde5589ebbaf.jpg)

**Comment by cookin2** [comment]
There's a message under NEWS on your tester's portal:
"Bonusing Issue 2016-10-28 19:47:11 UTC, Emanuel Evans
Hi all! We're experiencing issues around bonuses not going out. We haven't yet determined the root cause. If you haven't received bonuses for recent work, do not panic! We will backpay all bonuses that got skipped once the issue is resolved."

**Comment by RnkSts** [comment]
This is a place to post issues about the extension itself. Please take a look in the [**Forum**](forum.rainforestqa.com) for non-related extension issues :)
There's a topic about this bonus issue:
**https://forum.rainforestqa.com/t/bonuses-columns-showing/2523**

**Comment by teckda** [comment]
Thanks for the information of the problem and the use of this space.
