### ISSUE TITLE
Terminal - Mac OS X - Scroll Direction

### ISSUE THREAD

**Issue by Foreverrr** [rainforestapp/tester-chrome-extension#78]
I don't know if anyone asked a fix for this, but it's a simple fix...

As you probably know, Mac OS X has reverse scrolling than Windows, sometimes is quite frustrating since we need to scroll outside the terminal and then inside the terminal, this thing can be fixed pretty easy by changing the scrolling direction of Mac's terminals, I believe that you or the guys that provide you the VMs can change this settings for every Mac terminal and make it default so the scrolling direction to be same as Windows scrolling direction every time we get a Mac terminal...

**Comment by Deepak0988** [comment]
This will be very helpful if the scrolling direction remains same for Terminals (especially MAC) and Windows.

**Comment by helloworld111gh** [comment]
This fix would be great if it could be implemented.
Also, could it be made possible so when you scroll in the terminal it does
not affect the scroll outside the terminal? It's annoying to keep scrolling
up and down and I'm already using 75% zoom to make it easier for me.

**Comment by Foreverrr** [comment]
@helloworld111gh 

The scroll direction could be fixed very simple, they just need to edit the setting of each Mac terminal, there's an option in the Mac settings that can make scrolling direction the same as Windows scrolling direction...

The second one couldn't be really implemented, I don't really see how could it be implemented, we just need bigger screens :P

**Comment by JPierreS** [comment]
There is a quick fix everyone can use (until they fix this on their end)

Use your cursor keys.   To activate this, simply click on any non clickable link or area inside the
terminal (such as a background), then use the cursor UP / DOWN on your keyboard to scroll
up and down as you normally would using a mouse wheel, problem solved.  If you click on a
link or a forum / text entry or anything else, in order to scroll again using cursor keys you need to
apply the same thing, click on any background area in the site and repeat (cursor up / down).

This is a quick and easy fix until they fix this on their end.

**Comment by akshithaaravi** [comment]
JPierreS, I just got a hit with this terminal and I tried to follow your tip to scroll down, but it seems impossible, the screen is not responding any of the keys.

**Comment by JPierreS** [comment]
@akshithaaravi  It works but you have to click a background area first before using the up/down arrow keys on your keyboard, otherwise it won't scroll.  By clicking a background area, means any area that is not active (no image or link) - example a page that has a white background, click any area that is blank and then use up/down arrow.  I use this every day as I get a lot of jobs under MAC terminals.  Sometimes you have to tap the cursor keys several times for it to scroll (this is just a temp fix) you can use your mouse wheel but in reverse, but not too practical.

**Comment by JPierreS** [comment]
[](http://s12.postimg.org/jzs81y3d9/MACScroll.gif)

Test

**Comment by akshithaaravi** [comment]
Thank you for your tips, I will definitely try these when I get this hit.
