### ISSUE TITLE
Rejections tab seems to be missing content (and other bugs)

### ISSUE THREAD

**Issue by helloworld111gh** [rainforestapp/tester-chrome-extension#81]
The new rejections feature has quite a few bugs in it:
1. Rejected jobs seem to be missing the reason why they got rejected. A few of them have a step with a red X, ~~but most just have "job_step.answer_given" on all the steps, which seems that you made a variable a string.~~
2. The steps are out of order
3. The screenshots are poorly done, there is no difference between "copy this url and press take screenshot", actual steps, and test re-dos due to an error (which BTW can you add an undo feature to prevent HIT refreshes due to human error?)
APPEND: Also I would like to note that one of the factors to auto-reject (test question that asks if you are testing a website) should be removed, there was a worker who complained on a forum that they got rejected because they hit "no" on that question when they were testing a powerpoint extension.

**Comment by balajisekar** [comment]
You are right @helloworld111gh I am too getting this kind bug.

I can't understand what is given, why they rejected, etc.

**Comment by JPierreS** [comment]
In my opinion, might be a bad idea to show expired admin verified rejections, and show only the history for past 30 days only, these would be the standing internal rejections, also any new admin rejection from this point moving forward should provide an indication as to what step caused the rejection, as the page shows all the completed steps and screenshots.  Showing all the rejections as a total I think would confuse most people who are not aware that probably most of these rejections are expired.

**Comment by mojenLXXXIII** [comment]
Regarding red X answer those are verified admin rejections ,as for other Hit that only showing job_step.answer_given ,

I believe that RF is hiding the rejections on a step level for a reason as this will give us a hint of answers for workers we paired with  , some workers will depend on such results in case they work on the same rejected Hit again , which is not the purpose of testing as we all know.

**Comment by cookin2** [comment]
@JPierreS's suggestion makes a lot of sense to me, and I as well as many of my fellow RF members would benefit greatly from this.  Please consider it :)

**Comment by pscohn** [comment]
There's currently a bug that doesn't show your answers correctly, which will be fixed on the next release (Monday).

@JPierreS, I agree with you, we'll change it to show only the last 30 days of rejections.

**Comment by Genesis2015** [comment]
@pscohn Could you provide the ability to us to see for which sites we are blocked to do tests? I'm sure I've blocked to do tests to Аttend because I have not had any since the end of November. How do I know if I'm blocked on other "test providers" :)

**Comment by diabolic012** [comment]
i have some rejected jobs for example:

Add 465 and 642 using a calculator. 
Is the sum 1107?

I answered Yes but no, it is rejected ?!

**Comment by braneb** [comment]
@Genesis2015 How can you be blocked for one particular site...is that even possible?

**Comment by warpten09025** [comment]
@diabolic012 : i don't think you got rejected because of test question . Sometimes the test only tell you to look at the page , but you need to do some action to change the view of the page because if too many same screenshot in one test = automatic rejection. ( I guess 3 same screenshot will be okay , but when u take 4 same screenshots in 1 test the system will reject your work )

Genesis2015 : I think you're blocked because you got 20 rejections in just 1 month  or test author really blocked you and your account is blocked !

**Comment by ando100** [comment]
@warpten09025  maybe no and no
1. @diabolic012 answered incorrectly to this test question or some
     other test question in this test, at the moment things are a bit messy and
     as @pscohn said- will be corrected on monday. 
2. @Genesis2015  can work on tasks, but not in this particular he named, so 
    TA has blocked him, very possible reason- TA did not accept his work.
@Genesis2015 - What will you do with that information? So you get
info that this TA has blocked you- what will you do next?  TA will not unblock you.
It does not help you in any good way, only your frustration level will rise.  
So I assume, yes you were blocked, when you see other people are talking
about tasks you can not see in your tasks list.
Just be more careful in the future.

**Comment by JPierreS** [comment]
@warpten09025  - If you fail any of the QC / anti bot / math questions you still can continue the test to the end and get paid, however you will get an automatic internal rejection.  TIP, always use a calculator and take your time on these questions.  Some might seem like an obvious answer, but aren't, safer to use a calculator.   For the rest, authors can LIKE or BAN you, if they ban you, it means you can continue working on other tests, but you are no longer going to receive work from that author.  A GOOD way to risk author bans is to click YES instead of reporting or not following instructions. :)   
As far as the rest, always treat every single test as if you have done it for the first time, interact properly in the terminal and take reasonable time.  In theory, you can get all the answers right, but speed through and not interact, that could give you admin rejection too :)  So one should not assume because you did the test 40 times that it will always pass all the way !     
as far as the blocking threshold, you can get blocked much sooner too :)
I think the whole point of this is to reassure those of us who are doing a good job and honest job to continue, that everything is ok, and that we are not getting those secret admin rejections in the background :D  Whilst, the "YES" workers get an idea that 1) authors can ban 2) they will eventually get caught 3) their jobs checked more if they do and blocked.   As far as UNFAIR rejections no system is perfect, I'm sure some of those auto admins can be given in error, I have a good idea why too :) but the good news is the threshold is such to allow such errors , even human mistakes and correct them as necessary.   (I,ve tripped on some math questions in the past too )

**Comment by nerdatwork** [comment]
Also it needs a way to **appeal** rejections by which testers can justify what happened and why they answered it which got them rejected.

**Comment by pscohn** [comment]
FYI, the bug fixing the display of your answer given should be fixed.

@nerdatwork, we're not planning on adding this since the A) it would add a lot of support volume for us and B) rejections matter mainly testers who have actually been blocked, otherwise we show them to you so you can see your mistakes and improve. If you do get blocked, we'll take a look at the rejections to make sure the block is fair. If you aren't sure why a job was rejected, we'll explain that as well so we can help testers from continuing to make the same mistakes.

**Comment by JPierreS** [comment]
@nerdatwork  I'm afraid not :)   I've been down that road before in regards to admin rejections.  You cannot dispute or have admin rejections overturned.  Furthermore, there is no use to disputing expired admin rejections.   The ones that are unfair are rare, in such a way you should not accumulate a high enough amount to cause you a block, unless you purposely do bad work.    the most admins I have had in a 30 days period was 4.   Your admin rejections are reviewed only if you are blocked - until then they do not affect your account or amount of jobs you get - though out of my 15 total there are many I would also love re-checked as well but I guess that can't happen  ;-)))

**Comment by nerdatwork** [comment]
@pscohn @JPierreS I understand but I wasnt saying that about me just in general. Also on a totally different note. The total amount of jobs done shown DO NOT MATCH with the history entries.

**Comment by JPierreS** [comment]
@nerdatwork   The total shown in your profile is TOTAL JOBS, and not total jobs completed.  The moment you open an active job it will count towards the total (so all abandoned and uncompleted ones) also go to your total.  So your total jobs will likely be much higher than what is shown in your history (the history only shows you COMPLETED jobs).   Perhaps they should change this total jobs to show only those that were COMPLETED, and not include abandoned or non completed jobs (due to errors, losing hits, etc.)

**Comment by nerdatwork** [comment]
@JPierreS I know that and that absolutely makes no sense. What am I going to do with jobs counted that are abandoned or uncompleted ? I want to know how many jobs are completed thats it.

**Comment by JPierreS** [comment]
@nerdatwork    Exactly, as  for some extreme reasons sometimes a job gets abandoned or cannot be completed or LOST due to too many restarts, so those go towards your total.  This is one of the reasons why the % that was shown in the portal was lower for most people than what it should be.   I agree that we should only be shown our total jobs completed, and not total jobs opened, or simply add another entry "total jobs completed"

**Comment by pscohn** [comment]
@nerdatwork @JPierreS we can look at possibly changing this count to "total jobs completed" this week.

**Comment by warpten09025** [comment]
Test questions are easy bro , 1 answer is yes and 1 is no .. It's hard to fail test questions !
I don't know RQA changed it or not , but in the past even you have all answers right but if you have too many same screenshots you will be auto reject by system ( i don't recall it is 4 or 5 same screenshots , and if there is a minor different like page zoom , ... system will accept this work ) ....
You work can also be rejected because you have different answers from other people , too ( compare to at least 2 other people , long time ago my work get compared with 10 people or more ) ..
My work also got rejected by admin ( but i still can do test for that site  ) . And my rejection for that month is 1/20 , then next month it reseted to 0 so my rejection came back 0/20 .....

All i want to do is prove that my answer is right dancers:  because i have many experiences in the past +1: !

**Comment by RezwanulHaque** [comment]
Its good to have this option in the dashboard. We will know if we are doing mistake and will be aware. I know nobody do mistake intentionally.

**Comment by JPierreS** [comment]
@RezwanulHaque : Not only helpful to prevent future mistakes, BUT also as an indication to those cheating to be aware that admins check jobs, and the more they get caught, the more their jobs are likely to be checked - so it serves 2 purposes really.

As of today the total jobs was adjusted, so you should notice an increase in the number.
Also rejections now show only the past 30 days, so this value should go down over time.  This is one area where you want to see LOW numbers ;-)

Regarding the total jobs completed there might still be an issue.
It might still be showing more jobs than the total from history, but by a small amount.

Example, total jobs 10929, but in history 10927 counted (taking each page x 25) and manually counting last page.
